import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import type { EmitterContext, ApiSpec, Model, Enum } from '@workos/oagen';
import { defaultSdkBehavior } from '@workos/oagen';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { generateModels } from '../../src/go/models.js';
import { generateEnums } from '../../src/go/enums.js';

const emptySpec: ApiSpec = {
  name: 'Test',
  version: '1.0.0',
  baseUrl: '',
  services: [],
  models: [],
  enums: [],
  sdk: defaultSdkBehavior(),
};

function strField(name: string, required = true) {
  return { name, type: { kind: 'primitive', type: 'string' } as const, required };
}

let outputDir: string;

beforeEach(() => {
  outputDir = mkdtempSync(join(tmpdir(), 'oagen-go-scope-'));
});
afterEach(() => {
  rmSync(outputDir, { recursive: true, force: true });
});

/** Build a scoped EmitterContext pointing at the temp outputDir. */
function scopedCtx(opts: {
  spec?: ApiSpec;
  scopedServices: string[];
  scopedModelNames?: string[];
  scopedEnumNames?: string[];
  priorManifestPaths: string[];
}): EmitterContext {
  return {
    namespace: 'workos',
    namespacePascal: 'WorkOS',
    spec: opts.spec ?? emptySpec,
    outputDir,
    scopedServices: new Set(opts.scopedServices),
    scopedModelNames: opts.scopedModelNames ? new Set(opts.scopedModelNames) : undefined,
    scopedEnumNames: opts.scopedEnumNames ? new Set(opts.scopedEnumNames) : undefined,
    priorTargetManifestPaths: new Set(opts.priorManifestPaths),
  };
}

function writePrior(relPath: string, content: string) {
  const abs = join(outputDir, relPath);
  mkdirSync(join(abs, '..'), { recursive: true });
  writeFileSync(abs, content, 'utf-8');
}

describe('go scoped flat-file reconciliation (models.go)', () => {
  it('drops a brand-new out-of-scope model (ADDITION fix / Option B)', () => {
    // Prior models.go has only InScopeThing. The new spec adds OutOfScopeNew,
    // which belongs to a service NOT selected this run.
    writePrior(
      'models.go',
      [
        '// Code generated by oagen. DO NOT EDIT.',
        '',
        'package workos',
        '',
        '// InScopeThing represents an in scope thing.',
        'type InScopeThing struct {',
        '\tID string `json:"id"`',
        '}',
        '',
      ].join('\n'),
    );

    const models: Model[] = [
      { name: 'InScopeThing', fields: [strField('id')] },
      // Structurally distinct so a "missing" result can't be confused with dedup.
      { name: 'OutOfScopeNew', fields: [strField('id'), strField('extra')] },
    ];
    const ctx = scopedCtx({
      scopedServices: ['InScope'],
      scopedModelNames: ['InScopeThing'], // OutOfScopeNew NOT in scope
      priorManifestPaths: ['models.go'],
    });

    const content = generateModels(models, ctx)[0].content;
    expect(content).toContain('type InScopeThing struct {');
    // Brand-new out-of-scope model must NOT be added to the flat file.
    expect(content).not.toContain('OutOfScopeNew');
  });

  it('retains a renamed/removed type still referenced by out-of-scope code (REMOVAL fix)', () => {
    // Prior models.go has OrganizationDomainStandAlone. The new spec renamed it
    // to OrganizationDomain (so the old name is gone from the model set), and
    // OrganizationDomain belongs to an out-of-scope service. The old name must
    // be carried over so out-of-scope resource code keeps compiling.
    writePrior(
      'models.go',
      [
        '// Code generated by oagen. DO NOT EDIT.',
        '',
        'package workos',
        '',
        '// InScopeThing represents an in scope thing.',
        'type InScopeThing struct {',
        '\tID string `json:"id"`',
        '}',
        '',
        '// OrganizationDomainStandAlone represents an organization domain stand alone.',
        'type OrganizationDomainStandAlone struct {',
        '\tID string `json:"id"`',
        '\tDomain string `json:"domain"`',
        '}',
        '',
      ].join('\n'),
    );

    const models: Model[] = [
      { name: 'InScopeThing', fields: [strField('id')] },
      // The renamed model exists in the new spec but is out of scope this run.
      { name: 'OrganizationDomain', fields: [strField('id'), strField('domain')] },
    ];
    const ctx = scopedCtx({
      scopedServices: ['InScope'],
      scopedModelNames: ['InScopeThing'],
      priorManifestPaths: ['models.go'],
    });

    const content = generateModels(models, ctx)[0].content;
    expect(content).toContain('type InScopeThing struct {');
    // The renamed-away type is preserved verbatim from the prior file.
    expect(content).toContain('type OrganizationDomainStandAlone struct {');
    // The new out-of-scope rename is NOT freshly added (it didn't exist before).
    expect(content).not.toContain('type OrganizationDomain struct {');
  });

  it('regenerates an in-scope model with its new fields', () => {
    writePrior(
      'models.go',
      [
        'package workos',
        '',
        '// InScopeThing represents an in scope thing.',
        'type InScopeThing struct {',
        '\tID string `json:"id"`',
        '}',
        '',
      ].join('\n'),
    );

    const models: Model[] = [{ name: 'InScopeThing', fields: [strField('id'), strField('new_field')] }];
    const ctx = scopedCtx({
      scopedServices: ['InScope'],
      scopedModelNames: ['InScopeThing'],
      priorManifestPaths: ['models.go'],
    });

    const content = generateModels(models, ctx)[0].content;
    expect(content).toContain('NewField string `json:"new_field"`');
  });

  it('force-retains an out-of-scope canonical referenced by an in-scope alias', () => {
    // Two structurally-identical models. The alphabetically-first is the dedup
    // canonical but is brand-new AND out of scope; the other is in scope and is
    // emitted as `type InScopeAliasModel = AaaCanonical`. Without force-retain
    // the canonical would be dropped, leaving the alias dangling
    // (undefined: AaaCanonical) and the package failing to build.
    writePrior('models.go', ['package workos', ''].join('\n'));

    const fields = [strField('id'), strField('label')];
    const models: Model[] = [
      { name: 'AaaCanonical', fields }, // sorts first -> canonical; out of scope, brand-new
      { name: 'InScopeAliasModel', fields }, // in scope -> alias to AaaCanonical
    ];
    const ctx = scopedCtx({
      scopedServices: ['InScope'],
      scopedModelNames: ['InScopeAliasModel'],
      priorManifestPaths: ['models.go'],
    });

    const content = generateModels(models, ctx)[0].content;
    expect(content).toContain('type InScopeAliasModel = AaaCanonical');
    // The canonical must be present so the alias resolves.
    expect(content).toContain('type AaaCanonical struct {');
  });

  it('full run (no scoping) emits every model unchanged', () => {
    const models: Model[] = [
      { name: 'InScopeThing', fields: [strField('id')] },
      // Structurally distinct so it isn't deduped into a type alias.
      { name: 'OutOfScopeNew', fields: [strField('id'), strField('extra')] },
    ];
    const ctx: EmitterContext = { namespace: 'workos', namespacePascal: 'WorkOS', spec: emptySpec };
    const content = generateModels(models, ctx)[0].content;
    expect(content).toContain('type InScopeThing struct {');
    expect(content).toContain('type OutOfScopeNew struct {');
  });
});

describe('go scoped flat-file reconciliation (enums.go)', () => {
  it('drops a brand-new out-of-scope enum and retains a renamed-away one', () => {
    writePrior(
      'enums.go',
      [
        'package workos',
        '',
        '// InScopeStatus represents in scope status values.',
        'type InScopeStatus string',
        '',
        'const (',
        '\tInScopeStatusActive InScopeStatus = "active"',
        ')',
        '',
        '// OldRenamedState represents old renamed state values.',
        'type OldRenamedState string',
        '',
        'const (',
        '\tOldRenamedStatePending OldRenamedState = "pending"',
        ')',
        '',
      ].join('\n'),
    );

    const enums: Enum[] = [
      { name: 'InScopeStatus', values: [{ name: 'active', value: 'active' }] },
      // brand-new, out of scope
      { name: 'OutOfScopeNewEnum', values: [{ name: 'x', value: 'x' }] },
      // renamed away: OldRenamedState -> NewRenamedState (out of scope)
      { name: 'NewRenamedState', values: [{ name: 'pending', value: 'pending' }] },
    ];
    const ctx = scopedCtx({
      scopedServices: ['InScope'],
      scopedEnumNames: ['InScopeStatus'],
      priorManifestPaths: ['enums.go'],
    });

    const content = generateEnums(enums, ctx).find((f) => f.path === 'enums.go')!.content;
    expect(content).toContain('type InScopeStatus string');
    // brand-new out-of-scope enum dropped
    expect(content).not.toContain('type OutOfScopeNewEnum string');
    // renamed-away enum retained verbatim from prior file
    expect(content).toContain('type OldRenamedState string');
    // the new (out-of-scope) name is not freshly added
    expect(content).not.toContain('type NewRenamedState string');
  });

  it('force-retains an out-of-scope canonical enum referenced by an in-scope alias', () => {
    writePrior('enums.go', ['package workos', ''].join('\n'));

    const enums: Enum[] = [
      // identical values -> deduped; alphabetically-first is the canonical
      { name: 'AaaCanonicalStatus', values: [{ name: 'active', value: 'active' }] }, // out of scope, brand-new
      { name: 'InScopeAliasStatus', values: [{ name: 'active', value: 'active' }] }, // in scope -> alias
    ];
    const ctx = scopedCtx({
      scopedServices: ['InScope'],
      scopedEnumNames: ['InScopeAliasStatus'],
      priorManifestPaths: ['enums.go'],
    });

    const content = generateEnums(enums, ctx).find((f) => f.path === 'enums.go')!.content;
    expect(content).toContain('type InScopeAliasStatus = AaaCanonicalStatus');
    // The canonical enum must be present so the alias resolves.
    expect(content).toContain('type AaaCanonicalStatus string');
  });
});

describe('go scoped flat-file reconciliation (events.go)', () => {
  it('keeps the prior event const set: drops new events, retains existing', () => {
    writePrior(
      'pkg/events/events.go',
      [
        'package events',
        '',
        '// Event is a WorkOS event type.',
        'type Event string',
        '',
        'const (',
        '\tOrganizationCreated = "organization.created"',
        ')',
        '',
      ].join('\n'),
    );

    const enums: Enum[] = [
      {
        name: 'CreateWebhookEndpointEvents',
        values: [
          { name: 'organization.created', value: 'organization.created' },
          // brand-new event from an out-of-scope service
          { name: 'session.reauthenticated', value: 'session.reauthenticated' },
        ],
      },
    ];
    const ctx = scopedCtx({
      scopedServices: ['InScope'],
      priorManifestPaths: ['pkg/events/events.go'],
    });

    const events = generateEnums(enums, ctx).find((f) => f.path === 'pkg/events/events.go')!.content;
    expect(events).toContain('OrganizationCreated = "organization.created"');
    // brand-new out-of-scope event must not be added to the flat events file
    expect(events).not.toContain('session.reauthenticated');
  });

  it('full run emits all events', () => {
    const enums: Enum[] = [
      {
        name: 'CreateWebhookEndpointEvents',
        values: [
          { name: 'organization.created', value: 'organization.created' },
          { name: 'session.reauthenticated', value: 'session.reauthenticated' },
        ],
      },
    ];
    const ctx: EmitterContext = { namespace: 'workos', namespacePascal: 'WorkOS', spec: emptySpec };
    const events = generateEnums(enums, ctx).find((f) => f.path === 'pkg/events/events.go')!.content;
    expect(events).toContain('organization.created');
    expect(events).toContain('session.reauthenticated');
  });
});
