import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { execFileSync } from 'node:child_process';
import type { ApiSpec, EmitterContext, Operation, Service } from '@workos/oagen';
import { defaultSdkBehavior } from '@workos/oagen';

import {
  buildLiveSurface,
  emptyLiveSurface,
  mergeGeneratedClassMethodsIntoExisting,
  pathExists,
  shouldSkipPath,
} from '../../src/node/live-surface.js';
import { nodeEmitter } from '../../src/node/index.js';

let tmpRoot: string;

beforeAll(() => {
  tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'live-surface-'));
  const src = path.join(tmpRoot, 'src');
  fs.mkdirSync(path.join(src, 'organizations', 'interfaces'), { recursive: true });
  fs.mkdirSync(path.join(src, 'common', 'utils'), { recursive: true });
  fs.mkdirSync(path.join(src, 'webhooks'), { recursive: true });

  // Plain hand-written class file (no header, no marker)
  fs.writeFileSync(
    path.join(src, 'organizations', 'organizations.ts'),
    [
      "import { WorkOS } from '../workos.js';",
      'export class Organizations {',
      '  constructor(private workos: WorkOS) {}',
      '  async listOrganizations(options?: { limit?: number }) {',
      '    return this.workos.get("/organizations", options);',
      '  }',
      '  async getOrganization(id: string) {',
      '    return this.workos.get(`/organizations/${id}`);',
      '  }',
      '}',
    ].join('\n'),
  );

  fs.writeFileSync(
    path.join(src, 'organizations', 'interfaces', 'organization.interface.ts'),
    [
      'export interface Organization {',
      '  id: string;',
      '  name: string;',
      '  createdAt: string;',
      '}',
      '',
      'export interface OrganizationResponse {',
      '  id: string;',
      '  name: string;',
      "  'created_at': string;",
      '}',
      '',
      'export type Status = "active" | "suspended";',
    ].join('\n'),
  );

  // Auto-generated file (header present, no ignore marker)
  fs.mkdirSync(path.join(src, 'admin-portal'), { recursive: true });
  fs.writeFileSync(
    path.join(src, 'admin-portal', 'admin-portal.ts'),
    [
      '// This file is auto-generated by oagen. Do not edit.',
      "import { WorkOS } from '../workos.js';",
      'export class AdminPortal {',
      '  constructor(private workos: WorkOS) {}',
      '  async generateLink(opts: { adminEmails?: string[] }) { return opts; }',
      '}',
    ].join('\n'),
  );

  // Const-object enum (workos-node house style) with acronym casing.
  fs.mkdirSync(path.join(src, 'common', 'interfaces'), { recursive: true });
  fs.writeFileSync(
    path.join(src, 'common', 'interfaces', 'generate-link-intent.interface.ts'),
    [
      '// This file is auto-generated by oagen. Do not edit.',
      '',
      'export const GenerateLinkIntent = {',
      "  SSO: 'sso',",
      "  DSync: 'dsync',",
      "  AuditLogs: 'audit_logs',",
      '} as const;',
      'export type GenerateLinkIntent = (typeof GenerateLinkIntent)[keyof typeof GenerateLinkIntent];',
    ].join('\n'),
  );

  // Protected file
  fs.writeFileSync(
    path.join(src, 'webhooks', 'webhooks.ts'),
    [
      '// @oagen-ignore-file',
      'export class Webhooks {',
      '  verifySignature(payload: string) { return true; }',
      '}',
    ].join('\n'),
  );

  fs.writeFileSync(
    path.join(src, 'common', 'utils', 'pagination.ts'),
    [
      '// @oagen-ignore-file',
      'export function autoPaginate<T>(input: T[]): T[] { return input; }',
      'export async function fetchPage(url: string) { return { data: [], after: null }; }',
    ].join('\n'),
  );

  // A spec file that should be ignored
  fs.writeFileSync(
    path.join(src, 'organizations', 'organizations.spec.ts'),
    ["import { Organizations } from './organizations.js';", "describe('x', () => { it('y', () => {}) })"].join('\n'),
  );

  execFileSync('git', ['init'], { cwd: tmpRoot, stdio: 'ignore' });
  execFileSync('git', ['add', 'src'], { cwd: tmpRoot, stdio: 'ignore' });
  fs.mkdirSync(path.join(src, 'connect'), { recursive: true });
  fs.writeFileSync(path.join(src, 'connect', 'connect.ts'), 'export class Connect {}');
});

afterAll(() => {
  fs.rmSync(tmpRoot, { recursive: true, force: true });
});

describe('buildLiveSurface', () => {
  it('returns an empty surface when src/ is missing', () => {
    const empty = fs.mkdtempSync(path.join(os.tmpdir(), 'no-src-'));
    try {
      const surface = buildLiveSurface(empty);
      expect(surface.files.size).toBe(0);
      expect(surface.classes.size).toBe(0);
      expect(surface.interfaces.size).toBe(0);
    } finally {
      fs.rmSync(empty, { recursive: true, force: true });
    }
  });

  it('records files relative to root with POSIX separators', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.files.has('src/organizations/organizations.ts')).toBe(true);
    expect(surface.files.has('src/organizations/interfaces/organization.interface.ts')).toBe(true);
    expect(surface.files.has('src/webhooks/webhooks.ts')).toBe(true);
  });

  it('distinguishes git-tracked baseline files from untracked junk', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.trackedFiles.has('src/organizations/organizations.ts')).toBe(true);
    expect(surface.trackedFiles.has('src/connect/connect.ts')).toBe(false);
  });

  it('does not parse declarations from untracked files when git baseline exists', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.classes.has('Connect')).toBe(false);
  });

  it('detects @oagen-ignore-file markers', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.protectedFiles.has('src/webhooks/webhooks.ts')).toBe(true);
    expect(surface.protectedFiles.has('src/common/utils/pagination.ts')).toBe(true);
    expect(surface.protectedFiles.has('src/organizations/organizations.ts')).toBe(false);
  });

  it('detects auto-generated header', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.autogenFiles.has('src/admin-portal/admin-portal.ts')).toBe(true);
    expect(surface.autogenFiles.has('src/organizations/organizations.ts')).toBe(false);
    // Protected files are NOT also recorded as autogen even if their content
    // happens to mention the phrase — the marker takes precedence.
    expect(surface.autogenFiles.has('src/webhooks/webhooks.ts')).toBe(false);
  });

  it('extracts exported class names with their methods', () => {
    const surface = buildLiveSurface(tmpRoot);
    const orgs = surface.classes.get('Organizations');
    expect(orgs).toBeDefined();
    expect(orgs?.filePath).toBe('src/organizations/organizations.ts');
    expect(orgs?.methods.has('listOrganizations')).toBe(true);
    expect(orgs?.methods.has('getOrganization')).toBe(true);
  });

  it('extracts protected class declarations as well', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.classes.get('Webhooks')?.filePath).toBe('src/webhooks/webhooks.ts');
  });

  it('extracts exported interface names with their fields', () => {
    const surface = buildLiveSurface(tmpRoot);
    const org = surface.interfaces.get('Organization');
    expect(org?.filePath).toBe('src/organizations/interfaces/organization.interface.ts');
    expect(org?.fields.has('id')).toBe(true);
    expect(org?.fields.has('name')).toBe(true);
    expect(org?.fields.has('createdAt')).toBe(true);

    const wire = surface.interfaces.get('OrganizationResponse');
    expect(wire?.fields.has('created_at')).toBe(true);
  });

  it('records exported type aliases', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.interfaces.has('Status')).toBe(true);
  });

  it('records exported functions', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.functions.get('autoPaginate')).toBe('src/common/utils/pagination.ts');
    expect(surface.functions.get('fetchPage')).toBe('src/common/utils/pagination.ts');
  });

  it('extracts const-object enum members with acronym casing preserved', () => {
    const surface = buildLiveSurface(tmpRoot);
    const members = surface.constObjectEnums.get('GenerateLinkIntent');
    expect(members).toBeDefined();
    expect(members?.get('sso')).toBe('SSO');
    expect(members?.get('dsync')).toBe('DSync');
    expect(members?.get('audit_logs')).toBe('AuditLogs');
  });

  it('skips .spec.ts files when extracting symbols', () => {
    const surface = buildLiveSurface(tmpRoot);
    // The spec file is recorded in files but its symbols are not parsed (no class extraction).
    expect(surface.files.has('src/organizations/organizations.spec.ts')).toBe(true);
    // No class declarations exist in the spec file anyway, so no false-positive check needed.
  });
});

describe('helpers', () => {
  it('shouldSkipPath returns true for protected files', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(shouldSkipPath(surface, 'src/webhooks/webhooks.ts')).toBe(true);
    expect(shouldSkipPath(surface, 'src/organizations/organizations.ts')).toBe(false);
  });

  it('pathExists reflects walked file set', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(pathExists(surface, 'src/organizations/organizations.ts')).toBe(true);
    expect(pathExists(surface, 'src/missing/file.ts')).toBe(false);
  });

  it('emptyLiveSurface produces a usable zero state', () => {
    const surface = emptyLiveSurface();
    expect(surface.files.size).toBe(0);
    expect(shouldSkipPath(surface, 'anything')).toBe(false);
    expect(pathExists(surface, 'anything')).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Partial emission must never delete existing methods (workos-node api-keys
// regression): a NOT-owned, NOT-adopted service whose autogen-headed resource
// file already exists gets a "new operations only" emission from resources.ts.
// applyLiveSurface used to promote that partial file to a full overwrite,
// replacing a 4-method class with a 1-method class.
// ---------------------------------------------------------------------------

const baseSpec: ApiSpec = {
  name: 'Test',
  version: '1.0.0',
  baseUrl: '',
  services: [],
  models: [],
  enums: [],
  sdk: defaultSdkBehavior(),
};

const baseCtx: EmitterContext = {
  namespace: 'workos',
  namespacePascal: 'WorkOS',
  spec: baseSpec,
};

function makeOp(name: string, httpMethod: Operation['httpMethod'], opPath: string): Operation {
  return {
    name,
    httpMethod,
    path: opPath,
    pathParams: opPath.includes('{id}')
      ? [{ name: 'id', type: { kind: 'primitive', type: 'string' }, required: true }]
      : [],
    queryParams: [],
    headerParams: [],
    response: { kind: 'primitive', type: 'unknown' },
    errors: [],
    injectIdempotencyKey: false,
  };
}

const EXISTING_API_KEYS_CLASS = [
  '// This file is auto-generated by oagen. Do not edit.',
  '',
  "import { WorkOS } from '../workos';",
  'import {',
  '  ValidateApiKeyOptions,',
  '  ValidateApiKeyResponse,',
  "} from './interfaces/validate-api-key.interface';",
  '',
  'export class ApiKeys {',
  '  constructor(private readonly workos: WorkOS) {}',
  '',
  '  async createValidation(',
  '    payload: ValidateApiKeyOptions,',
  '  ): Promise<ValidateApiKeyResponse> {',
  "    const { data } = await this.workos.post('/api_keys/validations', payload);",
  '    return data;',
  '  }',
  '',
  '  /**',
  '   * Delete an API key',
  '   */',
  '  async deleteApiKey(id: string): Promise<void> {',
  '    await this.workos.delete(`/api_keys/${id}`);',
  '  }',
  '',
  '  async listOrganizationApiKeys(organizationId: string): Promise<unknown> {',
  '    return this.workos.get(`/organizations/${organizationId}/api_keys`);',
  '  }',
  '',
  '  async createOrganizationApiKey(organizationId: string): Promise<unknown> {',
  '    return this.workos.post(`/organizations/${organizationId}/api_keys`, {});',
  '  }',
  '}',
  '',
].join('\n');

function createApiKeysSdkRoot(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'node-partial-overwrite-'));
  fs.mkdirSync(path.join(root, 'src', 'api-keys'), { recursive: true });
  fs.writeFileSync(path.join(root, 'src', 'workos.ts'), '// @oagen-ignore-file\nexport class WorkOS {}\n');
  fs.writeFileSync(path.join(root, 'src', 'index.ts'), '// @oagen-ignore-file\n');
  fs.writeFileSync(path.join(root, 'src', 'api-keys', 'api-keys.ts'), EXISTING_API_KEYS_CLASS);
  execFileSync('git', ['init'], { cwd: root, stdio: 'ignore' });
  execFileSync('git', ['add', 'src'], { cwd: root, stdio: 'ignore' });
  return root;
}

function apiKeysBaselineSurface(): unknown {
  const method = (name: string) => [{ name, params: [], returnType: 'Promise<unknown>', async: true }];
  return {
    classes: {
      ApiKeys: {
        methods: {
          createValidation: method('createValidation'),
          deleteApiKey: method('deleteApiKey'),
          listOrganizationApiKeys: method('listOrganizationApiKeys'),
          createOrganizationApiKey: method('createOrganizationApiKey'),
        },
      },
    },
  };
}

describe('mergeGeneratedClassMethodsIntoExisting', () => {
  const existingFile = [
    '// This file is auto-generated by oagen. Do not edit.',
    '',
    "import { WorkOS } from '../workos';",
    'import {',
    '  ValidateApiKeyOptions,',
    "} from './interfaces/validate-api-key.interface';",
    '',
    'export class ApiKeys {',
    '  constructor(private readonly workos: WorkOS) {}',
    '',
    '  async createValidation(payload: ValidateApiKeyOptions): Promise<unknown> {',
    "    return this.workos.post('/api_keys/validations', payload);",
    '  }',
    '',
    '  async deleteApiKey(id: string): Promise<void> {',
    '    await this.workos.delete(`/api_keys/${id}`);',
    '  }',
    '}',
    '',
  ].join('\n');

  const partialEmission = [
    '// This file is auto-generated by oagen. Do not edit.',
    '',
    "import type { WorkOS } from '../workos';",
    "import { deserializeApiKeyExpire } from './serializers/api-key-expire.serializer';",
    '',
    'export class ApiKeys {',
    '  constructor(private readonly workos: WorkOS) {}',
    '',
    '  /** Expire an API key. */',
    '  async createApiKeyExpire(id: string): Promise<void> {',
    '    await this.workos.post(`/api_keys/${encodeURIComponent(id)}/expire`, {});',
    '  }',
    '}',
    '',
  ].join('\n');

  it('returns null when the generated class covers every existing method', () => {
    // Identical emission: nothing dropped → caller may overwrite.
    expect(mergeGeneratedClassMethodsIntoExisting(existingFile, existingFile)).toBeNull();
    // Superset emission (every existing method plus a new one): full
    // regenerations must keep flowing through the overwrite path so spec
    // renames and emitter improvements propagate.
    const supersetEmission = existingFile.replace(
      '  async deleteApiKey(id: string): Promise<void> {',
      ['  async createApiKeyExpire(id: string): Promise<void> {', '    return;', '  }', '', '  async deleteApiKey(id: string): Promise<void> {'].join('\n'),
    );
    expect(mergeGeneratedClassMethodsIntoExisting(existingFile, supersetEmission)).toBeNull();
  });

  it('returns null for files without classes (models, serializers)', () => {
    const iface = 'export interface ApiKey {\n  id: string;\n}\n';
    expect(mergeGeneratedClassMethodsIntoExisting(iface, 'export interface ApiKey {\n  name: string;\n}\n')).toBeNull();
  });

  it('appends generated-only methods and missing imports, preserving the rest verbatim', () => {
    const merged = mergeGeneratedClassMethodsIntoExisting(existingFile, partialEmission);
    expect(merged).not.toBeNull();
    // Existing methods and their bodies survive byte-for-byte.
    expect(merged).toContain('async createValidation(payload: ValidateApiKeyOptions): Promise<unknown> {');
    expect(merged).toContain('await this.workos.delete(`/api_keys/${id}`);');
    // The new method (with its doc comment) is appended inside the class.
    expect(merged).toContain('/** Expire an API key. */');
    expect(merged).toContain('async createApiKeyExpire(id: string): Promise<void> {');
    expect(merged!.indexOf('createApiKeyExpire')).toBeGreaterThan(merged!.indexOf('deleteApiKey'));
    // The class still closes exactly once after the appended method.
    expect(merged!.trimEnd().endsWith('}')).toBe(true);
    // Imports: the serializer import is added once; WorkOS is NOT re-imported
    // even though the generated file used the `import type` form.
    expect(merged!.match(/deserializeApiKeyExpire/g)).toHaveLength(1);
    expect(merged!.match(/from '\.\.\/workos'/g)).toHaveLength(1);
    // Multi-line existing import block is untouched.
    expect(merged).toContain("} from './interfaces/validate-api-key.interface';");
  });
});

describe('non-owned autogen resource regeneration', () => {
  const apiKeysService: Service = {
    name: 'ApiKeys',
    operations: [
      makeOp('createValidation', 'post', '/api_keys/validations'),
      makeOp('deleteApiKey', 'delete', '/api_keys/{id}'),
      makeOp('listOrganizationApiKeys', 'get', '/organizations/{id}/api_keys'),
      makeOp('createOrganizationApiKey', 'post', '/organizations/{id}/api_keys'),
      makeOp('createApiKeyExpire', 'post', '/api_keys/{id}/expire'),
    ],
  };

  it('keeps every existing method and appends the new operation', () => {
    const root = createApiKeysSdkRoot();
    try {
      const spec: ApiSpec = { ...baseSpec, services: [apiKeysService] };
      const result = nodeEmitter.generateResources(spec.services, {
        ...baseCtx,
        spec,
        outputDir: root,
        emitterOptions: { adoptMissingServices: true, ownedServices: ['Groups'] },
        apiSurface: apiKeysBaselineSurface(),
      } as EmitterContext);

      const file = result.find((f) => f.path === 'src/api-keys/api-keys.ts');
      expect(file).toBeDefined();
      // All four pre-existing methods survive the regeneration...
      expect(file!.content).toContain('async createValidation(');
      expect(file!.content).toContain('async deleteApiKey(');
      expect(file!.content).toContain('async listOrganizationApiKeys(');
      expect(file!.content).toContain('async createOrganizationApiKey(');
      // ...their bodies are preserved textually...
      expect(file!.content).toContain('await this.workos.delete(`/api_keys/${id}`);');
      // ...and the new operation is appended.
      expect(file!.content).toContain('async createApiKeyExpire(');
      // The existing import block is preserved.
      expect(file!.content).toContain("} from './interfaces/validate-api-key.interface';");
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  it('still fully overwrites when the emission covers every existing method', () => {
    const root = createApiKeysSdkRoot();
    try {
      // No apiSurface baseline → resources.ts emits the full class; the
      // overwrite path must stay intact so emitter improvements propagate.
      const spec: ApiSpec = { ...baseSpec, services: [apiKeysService] };
      const result = nodeEmitter.generateResources(spec.services, {
        ...baseCtx,
        spec,
        outputDir: root,
        emitterOptions: { adoptMissingServices: true },
      } as EmitterContext);

      const file = result.find((f) => f.path === 'src/api-keys/api-keys.ts');
      expect(file).toBeDefined();
      expect(file!.overwriteExisting).toBe(true);
      // Full regeneration: generated content replaces the file wholesale.
      expect(file!.content).toContain('async createApiKeyExpire(');
      expect(file!.content).not.toContain('await this.workos.delete(`/api_keys/${id}`);');
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });
});
