import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import { buildLiveSurface, emptyLiveSurface, pathExists, shouldSkipPath } from '../../src/node/live-surface.js';

let tmpRoot: string;

beforeAll(() => {
  tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'live-surface-'));
  const src = path.join(tmpRoot, 'src');
  fs.mkdirSync(path.join(src, 'organizations', 'interfaces'), { recursive: true });
  fs.mkdirSync(path.join(src, 'common', 'utils'), { recursive: true });
  fs.mkdirSync(path.join(src, 'webhooks'), { recursive: true });

  // Plain hand-written class file (no header, no marker)
  fs.writeFileSync(
    path.join(src, 'organizations', 'organizations.ts'),
    [
      "import { WorkOS } from '../workos.js';",
      'export class Organizations {',
      '  constructor(private workos: WorkOS) {}',
      '  async listOrganizations(options?: { limit?: number }) {',
      '    return this.workos.get("/organizations", options);',
      '  }',
      '  async getOrganization(id: string) {',
      '    return this.workos.get(`/organizations/${id}`);',
      '  }',
      '}',
    ].join('\n'),
  );

  fs.writeFileSync(
    path.join(src, 'organizations', 'interfaces', 'organization.interface.ts'),
    [
      'export interface Organization {',
      '  id: string;',
      '  name: string;',
      '  createdAt: string;',
      '}',
      '',
      'export interface OrganizationResponse {',
      '  id: string;',
      '  name: string;',
      "  'created_at': string;",
      '}',
      '',
      'export type Status = "active" | "suspended";',
    ].join('\n'),
  );

  // Auto-generated file (header present, no ignore marker)
  fs.mkdirSync(path.join(src, 'admin-portal'), { recursive: true });
  fs.writeFileSync(
    path.join(src, 'admin-portal', 'admin-portal.ts'),
    [
      '// This file is auto-generated by oagen. Do not edit.',
      "import { WorkOS } from '../workos.js';",
      'export class AdminPortal {',
      '  constructor(private workos: WorkOS) {}',
      '  async generateLink(opts: { adminEmails?: string[] }) { return opts; }',
      '}',
    ].join('\n'),
  );

  // Const-object enum (workos-node house style) with acronym casing.
  fs.mkdirSync(path.join(src, 'common', 'interfaces'), { recursive: true });
  fs.writeFileSync(
    path.join(src, 'common', 'interfaces', 'generate-link-intent.interface.ts'),
    [
      '// This file is auto-generated by oagen. Do not edit.',
      '',
      'export const GenerateLinkIntent = {',
      "  SSO: 'sso',",
      "  DSync: 'dsync',",
      "  AuditLogs: 'audit_logs',",
      '} as const;',
      'export type GenerateLinkIntent = (typeof GenerateLinkIntent)[keyof typeof GenerateLinkIntent];',
    ].join('\n'),
  );

  // Protected file
  fs.writeFileSync(
    path.join(src, 'webhooks', 'webhooks.ts'),
    [
      '// @oagen-ignore-file',
      'export class Webhooks {',
      '  verifySignature(payload: string) { return true; }',
      '}',
    ].join('\n'),
  );

  fs.writeFileSync(
    path.join(src, 'common', 'utils', 'pagination.ts'),
    [
      '// @oagen-ignore-file',
      'export function autoPaginate<T>(input: T[]): T[] { return input; }',
      'export async function fetchPage(url: string) { return { data: [], after: null }; }',
    ].join('\n'),
  );

  // A spec file that should be ignored
  fs.writeFileSync(
    path.join(src, 'organizations', 'organizations.spec.ts'),
    ["import { Organizations } from './organizations.js';", "describe('x', () => { it('y', () => {}) })"].join('\n'),
  );
});

afterAll(() => {
  fs.rmSync(tmpRoot, { recursive: true, force: true });
});

describe('buildLiveSurface', () => {
  it('returns an empty surface when src/ is missing', () => {
    const empty = fs.mkdtempSync(path.join(os.tmpdir(), 'no-src-'));
    try {
      const surface = buildLiveSurface(empty);
      expect(surface.files.size).toBe(0);
      expect(surface.classes.size).toBe(0);
      expect(surface.interfaces.size).toBe(0);
    } finally {
      fs.rmSync(empty, { recursive: true, force: true });
    }
  });

  it('records files relative to root with POSIX separators', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.files.has('src/organizations/organizations.ts')).toBe(true);
    expect(surface.files.has('src/organizations/interfaces/organization.interface.ts')).toBe(true);
    expect(surface.files.has('src/webhooks/webhooks.ts')).toBe(true);
  });

  it('detects @oagen-ignore-file markers', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.protectedFiles.has('src/webhooks/webhooks.ts')).toBe(true);
    expect(surface.protectedFiles.has('src/common/utils/pagination.ts')).toBe(true);
    expect(surface.protectedFiles.has('src/organizations/organizations.ts')).toBe(false);
  });

  it('detects auto-generated header', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.autogenFiles.has('src/admin-portal/admin-portal.ts')).toBe(true);
    expect(surface.autogenFiles.has('src/organizations/organizations.ts')).toBe(false);
    // Protected files are NOT also recorded as autogen even if their content
    // happens to mention the phrase — the marker takes precedence.
    expect(surface.autogenFiles.has('src/webhooks/webhooks.ts')).toBe(false);
  });

  it('extracts exported class names with their methods', () => {
    const surface = buildLiveSurface(tmpRoot);
    const orgs = surface.classes.get('Organizations');
    expect(orgs).toBeDefined();
    expect(orgs?.filePath).toBe('src/organizations/organizations.ts');
    expect(orgs?.methods.has('listOrganizations')).toBe(true);
    expect(orgs?.methods.has('getOrganization')).toBe(true);
  });

  it('extracts protected class declarations as well', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.classes.get('Webhooks')?.filePath).toBe('src/webhooks/webhooks.ts');
  });

  it('extracts exported interface names with their fields', () => {
    const surface = buildLiveSurface(tmpRoot);
    const org = surface.interfaces.get('Organization');
    expect(org?.filePath).toBe('src/organizations/interfaces/organization.interface.ts');
    expect(org?.fields.has('id')).toBe(true);
    expect(org?.fields.has('name')).toBe(true);
    expect(org?.fields.has('createdAt')).toBe(true);

    const wire = surface.interfaces.get('OrganizationResponse');
    expect(wire?.fields.has('created_at')).toBe(true);
  });

  it('records exported type aliases', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.interfaces.has('Status')).toBe(true);
  });

  it('records exported functions', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(surface.functions.get('autoPaginate')).toBe('src/common/utils/pagination.ts');
    expect(surface.functions.get('fetchPage')).toBe('src/common/utils/pagination.ts');
  });

  it('extracts const-object enum members with acronym casing preserved', () => {
    const surface = buildLiveSurface(tmpRoot);
    const members = surface.constObjectEnums.get('GenerateLinkIntent');
    expect(members).toBeDefined();
    expect(members?.get('sso')).toBe('SSO');
    expect(members?.get('dsync')).toBe('DSync');
    expect(members?.get('audit_logs')).toBe('AuditLogs');
  });

  it('skips .spec.ts files when extracting symbols', () => {
    const surface = buildLiveSurface(tmpRoot);
    // The spec file is recorded in files but its symbols are not parsed (no class extraction).
    expect(surface.files.has('src/organizations/organizations.spec.ts')).toBe(true);
    // No class declarations exist in the spec file anyway, so no false-positive check needed.
  });
});

describe('helpers', () => {
  it('shouldSkipPath returns true for protected files', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(shouldSkipPath(surface, 'src/webhooks/webhooks.ts')).toBe(true);
    expect(shouldSkipPath(surface, 'src/organizations/organizations.ts')).toBe(false);
  });

  it('pathExists reflects walked file set', () => {
    const surface = buildLiveSurface(tmpRoot);
    expect(pathExists(surface, 'src/organizations/organizations.ts')).toBe(true);
    expect(pathExists(surface, 'src/missing/file.ts')).toBe(false);
  });

  it('emptyLiveSurface produces a usable zero state', () => {
    const surface = emptyLiveSurface();
    expect(surface.files.size).toBe(0);
    expect(shouldSkipPath(surface, 'anything')).toBe(false);
    expect(pathExists(surface, 'anything')).toBe(false);
  });
});
