import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';

import { generateModels } from './models.js';
import { detectDiscriminators } from '../shared/model-utils.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';
/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

/**
 * Annotate models with implicit discriminator info (without full oneOf
 * field flattening which can break existing model structures/fixtures).
 */
function withDiscriminators(ctx: EmitterContext): EmitterContext {
  const annotated = detectDiscriminators(ctx.spec.models);
  if (annotated === ctx.spec.models) return ctx;
  const spec: ApiSpec = { ...ctx.spec, models: annotated };
  return { ...ctx, spec };
}

export const pythonEmitter: Emitter = {
  language: 'python',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    const annotated = detectDiscriminators(models);
    return ensureTrailingNewlines(generateModels(annotated, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateEnums(enums, ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, withDiscriminators(ctx)));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, withDiscriminators(ctx)));
  },

  generateErrors(): GeneratedFile[] {
    // _errors.py is now hand-maintained in the target SDK (@oagen-ignore-file)
    return [];
  },

  generateTypeSignatures(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    void spec;
    void ctx;
    // Python uses inline type annotations — no separate type signature files needed
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    // Use original spec for model filtering (requestOnlyModelNames etc.) but
    // annotate discriminator models so dispatch tests are generated.
    const annotated = detectDiscriminators(spec.models);
    // Only replace discriminator-annotated models, keep the rest unchanged
    // so request-only filtering and field-based logic work correctly.
    const annotatedByName = new Map(annotated.filter((m: any) => m.discriminator).map((m) => [m.name, m]));
    const testModels = spec.models.map((m) => annotatedByName.get(m.name) ?? m);
    const testSpec: ApiSpec = { ...spec, models: testModels };
    return ensureTrailingNewlines(generateTests(testSpec, { ...ctx, spec: testSpec }));
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateManifest(spec, ctx));
  },

  fileHeader(): string {
    return '# This file is auto-generated by oagen. Do not edit.';
  },

  formatCommand(_targetDir: string): FormatCommand | null {
    return {
      cmd: 'bash',
      args: [
        '-c',
        'PY_FILES=$(printf "%s\\n" "$@" | grep "\\.py$" || true); if [ -n "$PY_FILES" ]; then echo "$PY_FILES" | xargs ruff check --fix --quiet 2>/dev/null; echo "$PY_FILES" | xargs ruff format --quiet; fi',
        '--',
      ],
      batchSize: 1000,
    };
  },
};
