import type { Emitter, EmitterContext, GeneratedFile, ApiSpec, Model, Enum, Service } from '@workos/oagen';

import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateErrors } from './errors.js';
import { generateConfig } from './config.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';

/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const pythonEmitter: Emitter = {
  language: 'python',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateModels(models, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateEnums(enums, ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateErrors(ctx));
  },

  generateConfig(ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateConfig(ctx));
  },

  generateTypeSignatures(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    // Python uses inline type annotations — no separate type signature files needed
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateManifest(spec, ctx));
  },

  fileHeader(): string {
    return '# This file is auto-generated by oagen. Do not edit.';
  },
};
