/**
 * Canonical "do not edit" banner text shared by every emitter's
 * `fileHeader()`. The text is comment-syntax agnostic — each emitter prefixes
 * it with the appropriate comment marker for its language (`//`, `#`, etc.).
 *
 * Keeping this in one place prevents the wording from drifting between
 * languages (Go and Rust previously emitted a different banner).
 */
export const AUTOGEN_NOTICE = 'This file is auto-generated by oagen. Do not edit.';
