/**
 * Canonical "do not edit" banner text shared by every emitter's
 * `fileHeader()`. The text is comment-syntax agnostic — each emitter prefixes
 * it with the appropriate comment marker for its language (`//`, `#`, etc.).
 *
 * Keeping this in one place prevents the wording from drifting between
 * languages (Rust previously emitted a different banner).
 *
 * Go intentionally does NOT use this constant: its header must match the
 * standard `^// Code generated .* DO NOT EDIT\.$` marker that Go tooling
 * relies on to recognize generated files. See `src/go/index.ts`.
 */
export const AUTOGEN_NOTICE = 'This file is auto-generated by oagen. Do not edit.';
