import { describe, it, expect } from 'vitest';
import { generateModels } from '../../src/python/models.js';
import type { EmitterContext, ApiSpec, Model, Service } from '@workos/oagen';

const emptySpec: ApiSpec = {
  name: 'Test',
  version: '1.0.0',
  baseUrl: '',
  services: [],
  models: [],
  enums: [],
};

const ctx: EmitterContext = {
  namespace: 'workos',
  namespacePascal: 'WorkOS',
  spec: emptySpec,
};

describe('generateModels', () => {
  it('returns empty for no models', () => {
    expect(generateModels([], ctx)).toEqual([]);
  });

  it('generates a dataclass for a model', () => {
    const service: Service = {
      name: 'Organizations',
      operations: [
        {
          name: 'getOrganization',
          httpMethod: 'get',
          path: '/organizations/{id}',
          pathParams: [
            {
              name: 'id',
              type: { kind: 'primitive', type: 'string' },
              required: true,
            },
          ],
          queryParams: [],
          headerParams: [],
          response: { kind: 'model', name: 'Organization' },
          errors: [],
          injectIdempotencyKey: false,
        },
      ],
    };

    const models: Model[] = [
      {
        name: 'Organization',
        fields: [
          {
            name: 'id',
            type: { kind: 'primitive', type: 'string' },
            required: true,
          },
          {
            name: 'name',
            type: { kind: 'primitive', type: 'string' },
            required: true,
          },
          {
            name: 'created_at',
            type: { kind: 'primitive', type: 'string', format: 'date-time' },
            required: true,
          },
          {
            name: 'external_id',
            type: {
              kind: 'nullable',
              inner: { kind: 'primitive', type: 'string' },
            },
            required: false,
          },
        ],
      },
    ];

    const ctxWithServices: EmitterContext = {
      ...ctx,
      spec: { ...emptySpec, services: [service], models },
    };

    const files = generateModels(models, ctxWithServices);
    // Model file + barrel __init__.py (parent __init__.py is generated by generateServiceInits)
    expect(files.length).toBe(2);

    const modelFile = files.find((f) => f.path === 'src/workos/organizations/models/organization.py')!;
    expect(modelFile).toBeDefined();

    // Has dataclass decorator
    expect(modelFile.content).toContain('@dataclass');
    expect(modelFile.content).toContain('class Organization:');

    // Required fields
    expect(modelFile.content).toContain('    id: str');
    expect(modelFile.content).toContain('    name: str');
    expect(modelFile.content).toContain('from datetime import datetime');
    expect(modelFile.content).toContain('    created_at: datetime');

    // Optional/nullable field
    expect(modelFile.content).toContain('    external_id: Optional[str] = None');

    // from_dict method
    expect(modelFile.content).toContain('def from_dict(cls, data: Dict[str, Any])');
    expect(modelFile.content).toContain('datetime.fromisoformat(data["created_at"].replace("Z", "+00:00"))');
    expect(modelFile.content).toContain(
      'raise WorkOSError(f"Unexpected API response: missing field {e!s} in Organization") from e',
    );

    // to_dict method
    expect(modelFile.content).toContain('def to_dict(self) -> Dict[str, Any]:');
    expect(modelFile.content).toContain('result["created_at"] = self.created_at.isoformat()');
  });

  it('handles array fields with model refs', () => {
    const service: Service = {
      name: 'Organizations',
      operations: [
        {
          name: 'getOrganization',
          httpMethod: 'get',
          path: '/organizations/{id}',
          pathParams: [{ name: 'id', type: { kind: 'primitive', type: 'string' }, required: true }],
          queryParams: [],
          headerParams: [],
          response: { kind: 'model', name: 'Organization' },
          errors: [],
          injectIdempotencyKey: false,
        },
      ],
    };

    const models: Model[] = [
      {
        name: 'Organization',
        fields: [
          {
            name: 'id',
            type: { kind: 'primitive', type: 'string' },
            required: true,
          },
          {
            name: 'domains',
            type: {
              kind: 'array',
              items: { kind: 'model', name: 'OrganizationDomain' },
            },
            required: true,
          },
        ],
      },
      {
        name: 'OrganizationDomain',
        fields: [
          {
            name: 'id',
            type: { kind: 'primitive', type: 'string' },
            required: true,
          },
          {
            name: 'domain',
            type: { kind: 'primitive', type: 'string' },
            required: true,
          },
        ],
      },
    ];

    const ctxWithServices: EmitterContext = {
      ...ctx,
      spec: { ...emptySpec, services: [service], models },
    };

    const files = generateModels(models, ctxWithServices);
    // 2 model files + 1 barrel __init__.py (parent __init__.py is generated by generateServiceInits)
    expect(files.length).toBe(3);

    const orgFile = files.find((f) => f.path.includes('organization.py') && !f.path.includes('organization_domain'));
    expect(orgFile).toBeDefined();
    expect(orgFile!.content).toContain('domains: List["OrganizationDomain"]');
    expect(orgFile!.content).toContain('OrganizationDomain.from_dict(cast(Dict[str, Any], item))');
  });

  it('skips list wrapper and list metadata models', () => {
    const service: Service = {
      name: 'Organizations',
      operations: [
        {
          name: 'listOrganizations',
          httpMethod: 'get',
          path: '/organizations',
          pathParams: [],
          queryParams: [],
          headerParams: [],
          response: { kind: 'model', name: 'OrganizationList' },
          errors: [],
          injectIdempotencyKey: false,
          pagination: {
            strategy: 'cursor',
            param: 'after',
            dataPath: 'data',
            itemType: { kind: 'model', name: 'Organization' },
          },
        },
      ],
    };

    const models: Model[] = [
      {
        name: 'Organization',
        fields: [{ name: 'id', type: { kind: 'primitive', type: 'string' }, required: true }],
      },
      {
        name: 'OrganizationList',
        fields: [
          {
            name: 'data',
            type: { kind: 'array', items: { kind: 'model', name: 'Organization' } },
            required: true,
          },
          {
            name: 'list_metadata',
            type: { kind: 'model', name: 'ListMetadata' },
            required: true,
          },
        ],
      },
      {
        name: 'ListMetadata',
        fields: [
          { name: 'before', type: { kind: 'primitive', type: 'string' }, required: false },
          { name: 'after', type: { kind: 'primitive', type: 'string' }, required: false },
        ],
      },
    ];

    const ctxWithServices: EmitterContext = {
      ...ctx,
      spec: { ...emptySpec, services: [service], models },
    };

    const files = generateModels(models, ctxWithServices);
    const filePaths = files.map((f) => f.path);

    // Should generate Organization but NOT OrganizationList or ListMetadata
    expect(filePaths.some((p) => p.includes('organization.py'))).toBe(true);
    expect(filePaths.some((p) => p.includes('organization_list.py'))).toBe(false);
    expect(filePaths.some((p) => p.includes('list_metadata.py'))).toBe(false);

    // Barrel should not export the skipped models
    const barrel = files.find((f) => f.path.endsWith('__init__.py') && f.path.includes('models/'));
    expect(barrel).toBeDefined();
    expect(barrel!.content).not.toContain('OrganizationList');
    expect(barrel!.content).not.toContain('ListMetadata');
  });

  it('generates type alias for structurally identical models', () => {
    const service: Service = {
      name: 'Organizations',
      operations: [
        {
          name: 'getOrganization',
          httpMethod: 'get',
          path: '/organizations/{id}',
          pathParams: [{ name: 'id', type: { kind: 'primitive', type: 'string' }, required: true }],
          queryParams: [],
          headerParams: [],
          response: { kind: 'model', name: 'OrganizationDomain' },
          errors: [],
          injectIdempotencyKey: false,
        },
      ],
    };

    const models: Model[] = [
      {
        name: 'OrganizationDomain',
        fields: [
          { name: 'id', type: { kind: 'primitive', type: 'string' }, required: true },
          { name: 'domain', type: { kind: 'primitive', type: 'string' }, required: true },
        ],
      },
      {
        name: 'OrganizationDomainStandAlone',
        fields: [
          { name: 'id', type: { kind: 'primitive', type: 'string' }, required: true },
          { name: 'domain', type: { kind: 'primitive', type: 'string' }, required: true },
        ],
      },
    ];

    const ctxWithServices: EmitterContext = {
      ...ctx,
      spec: { ...emptySpec, services: [service], models },
    };

    const files = generateModels(models, ctxWithServices);

    // Canonical model should have a full dataclass
    const canonicalFile = files.find(
      (f) => f.path.includes('organization_domain.py') && !f.path.includes('stand_alone'),
    )!;
    expect(canonicalFile).toBeDefined();
    expect(canonicalFile.content).toContain('@dataclass');
    expect(canonicalFile.content).toContain('class OrganizationDomain:');

    // Alias model should be a type alias
    const aliasFile = files.find((f) => f.path.includes('organization_domain_stand_alone.py'))!;
    expect(aliasFile).toBeDefined();
    expect(aliasFile.content).toContain('OrganizationDomainStandAlone = OrganizationDomain');
    expect(aliasFile.content).not.toContain('@dataclass');
  });

  it('handles union fields with identical model variants in from_dict', () => {
    const service: Service = {
      name: 'Auth',
      operations: [
        {
          name: 'getFactor',
          httpMethod: 'get',
          path: '/auth/factors/{id}',
          pathParams: [{ name: 'id', type: { kind: 'primitive', type: 'string' }, required: true }],
          queryParams: [],
          headerParams: [],
          response: { kind: 'model', name: 'AuthenticationFactor' },
          errors: [],
          injectIdempotencyKey: false,
        },
      ],
    };

    const models: Model[] = [
      {
        name: 'AuthenticationFactor',
        fields: [
          { name: 'id', type: { kind: 'primitive', type: 'string' }, required: true },
          {
            name: 'totp',
            type: {
              kind: 'union',
              variants: [
                { kind: 'model', name: 'AuthenticationFactorTotp' },
                { kind: 'model', name: 'AuthenticationFactorTotp' },
              ],
            },
            required: false,
          },
        ],
      },
      {
        name: 'AuthenticationFactorTotp',
        fields: [
          { name: 'issuer', type: { kind: 'primitive', type: 'string' }, required: true },
          { name: 'user', type: { kind: 'primitive', type: 'string' }, required: true },
        ],
      },
    ];

    const ctxWithServices: EmitterContext = {
      ...ctx,
      spec: { ...emptySpec, services: [service], models },
    };

    const files = generateModels(models, ctxWithServices);
    const factorFile = files.find((f) => f.path.includes('authentication_factor.py') && !f.path.includes('totp'))!;
    expect(factorFile).toBeDefined();

    // Union of identical model refs should collapse in from_dict
    expect(factorFile.content).toContain('AuthenticationFactorTotp.from_dict');
    // Type annotation should be collapsed (no Union[Foo, Foo])
    expect(factorFile.content).toContain('Optional["AuthenticationFactorTotp"]');
    expect(factorFile.content).not.toContain('Union["AuthenticationFactorTotp", "AuthenticationFactorTotp"]');
  });

  it('handles map fields', () => {
    const service: Service = {
      name: 'Organizations',
      operations: [
        {
          name: 'getOrganization',
          httpMethod: 'get',
          path: '/organizations/{id}',
          pathParams: [{ name: 'id', type: { kind: 'primitive', type: 'string' }, required: true }],
          queryParams: [],
          headerParams: [],
          response: { kind: 'model', name: 'Organization' },
          errors: [],
          injectIdempotencyKey: false,
        },
      ],
    };

    const models: Model[] = [
      {
        name: 'Organization',
        fields: [
          {
            name: 'id',
            type: { kind: 'primitive', type: 'string' },
            required: true,
          },
          {
            name: 'metadata',
            type: {
              kind: 'map',
              valueType: { kind: 'primitive', type: 'string' },
            },
            required: false,
          },
        ],
      },
    ];

    const ctxWithServices: EmitterContext = {
      ...ctx,
      spec: { ...emptySpec, services: [service], models },
    };

    const files = generateModels(models, ctxWithServices);
    // 1 model file + 1 barrel __init__.py (parent __init__.py is generated by generateServiceInits)
    expect(files.length).toBe(2);
    const modelFile = files.find((f) => f.path.endsWith('organization.py'))!;
    expect(modelFile.content).toContain('metadata: Optional[Dict[str, str]] = None');
  });
});
