import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';

import { generateModels } from './models.js';
import { enrichModelsFromSpec, getSyntheticEnums } from '../shared/model-utils.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';

/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const goEmitter: Emitter = {
  language: 'go',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    // Enrich models by flattening oneOf/allOf+oneOf variant fields from the raw spec
    const enriched = enrichModelsFromSpec(models);
    return ensureTrailingNewlines(generateModels(enriched, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    // Merge synthetic enums produced during model enrichment (inline oneOf
    // definitions) so they get proper type definitions in enums.go.
    const syntheticEnums = getSyntheticEnums();
    return ensureTrailingNewlines(generateEnums([...enums, ...syntheticEnums], ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(): GeneratedFile[] {
    return [];
  },

  generateTypeSignatures(): GeneratedFile[] {
    // Go uses inline type annotations -- no separate type signature files needed
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateManifest(spec, ctx));
  },

  fileHeader(): string {
    return '// Code generated by oagen. DO NOT EDIT.';
  },

  formatCommand(targetDir: string): FormatCommand | null {
    // Pass targetDir as the first path so gofmt formats the entire directory
    // (including hand-maintained files), not just the generated file list.
    return {
      cmd: 'gofmt',
      args: ['-w', targetDir],
      batchSize: 999999,
    };
  },
};
