import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';

import { generateModels } from './models.js';
import { enrichModelsFromSpec, getSyntheticEnums } from '../shared/model-utils.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateTests } from './tests.js';
import { buildOperationsMap } from './manifest.js';

/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const goEmitter: Emitter = {
  language: 'go',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    // Enrich models by flattening oneOf/allOf+oneOf variant fields from the raw spec
    const enriched = enrichModelsFromSpec(models);
    // Go has no sum types, so discriminated union base models (e.g. EventSchema)
    // need their base fields preserved. enrichModelsFromSpec clears fields for
    // discriminated models so dispatcher-capable languages can generate sealed
    // classes; restore the original fields here since Go just emits flat structs.
    const originalByName = new Map(models.map((m) => [m.name, m]));
    const goModels = enriched.map((m) => {
      if ((m as any).discriminator && m.fields.length === 0) {
        const original = originalByName.get(m.name);
        if (original && original.fields.length > 0) {
          return { ...m, fields: original.fields };
        }
      }
      return m;
    });
    return ensureTrailingNewlines(generateModels(goModels, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    // Merge synthetic enums produced during model enrichment (inline oneOf
    // definitions) so they get proper type definitions in enums.go.
    const syntheticEnums = getSyntheticEnums();
    return ensureTrailingNewlines(generateEnums([...enums, ...syntheticEnums], ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(): GeneratedFile[] {
    return [];
  },

  generateTypeSignatures(): GeneratedFile[] {
    // Go uses inline type annotations -- no separate type signature files needed
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  buildOperationsMap(spec: ApiSpec, ctx: EmitterContext) {
    return buildOperationsMap(spec, ctx);
  },

  fileHeader(): string {
    return '// Code generated by oagen. DO NOT EDIT.';
  },

  formatCommand(_targetDir: string): FormatCommand | null {
    // oagen appends all generated file paths (including .json fixtures) to the
    // format command. gofmt errors on non-.go files, so filter them out.
    // Same pattern as the Python emitter's ruff wrapper.
    return {
      cmd: 'bash',
      args: [
        '-c',
        'GO_FILES=$(printf "%s\\n" "$@" | grep "\\.go$"); [ -n "$GO_FILES" ] && echo "$GO_FILES" | xargs gofmt -w',
        '--',
      ],
      batchSize: 999999,
    };
  },
};
