import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';
import fs from 'node:fs';
import path from 'node:path';

import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateTests } from './tests.js';
import { buildOperationsMap } from './manifest.js';
import { enrichModelsFromSpec, getSyntheticEnums } from '../shared/model-utils.js';

/** Ensure every generated file ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const kotlinEmitter: Emitter = {
  language: 'kotlin',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    const enriched = enrichModelsFromSpec(models);
    return ensureTrailingNewlines(generateModels(enriched, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    // Merge synthetic enums produced during model enrichment (inline oneOf
    // definitions) so they get proper enum class files.
    const syntheticEnums = getSyntheticEnums();
    return ensureTrailingNewlines(generateEnums([...enums, ...syntheticEnums], ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(_ctx: EmitterContext): GeneratedFile[] {
    // Exception hierarchy is hand-maintained in workos-kotlin (see Phase 2).
    return [];
  },

  generateTypeSignatures(): GeneratedFile[] {
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    // Pass enriched models so round-trip tests see the full field set
    // (including optional oneOf-enriched fields) and can filter accurately.
    const enrichedModels = enrichModelsFromSpec(spec.models);
    const enrichedSpec: ApiSpec = { ...spec, models: enrichedModels };
    return ensureTrailingNewlines(generateTests(enrichedSpec, { ...ctx, spec: enrichedSpec }));
  },

  buildOperationsMap(spec: ApiSpec, ctx: EmitterContext) {
    return buildOperationsMap(spec, ctx);
  },

  fileHeader(): string {
    return '// This file is auto-generated by oagen. Do not edit.';
  },

  formatCommand(targetDir: string): FormatCommand | null {
    // ktlint enforces a 140-char max line length that cannot be auto-corrected
    // by the Gradle plugin alone, but `./gradlew ktlintFormat` fixes most
    // violations (trailing whitespace, import ordering, etc.) across all
    // generated files. The file list appended by oagen is ignored — Gradle
    // reformats the whole source set.
    if (!fs.existsSync(path.join(targetDir, 'gradlew'))) return null;
    return {
      cmd: 'bash',
      args: ['-c', `cd ${JSON.stringify(targetDir)} && ./gradlew ktlintFormat --quiet 2>/dev/null; true`, '--'],
    };
  },
};
