import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';

import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';
import { enrichModelsFromSpec } from '../shared/model-utils.js';

/** Ensure every generated file ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const kotlinEmitter: Emitter = {
  language: 'kotlin',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    const enriched = enrichModelsFromSpec(models);
    return ensureTrailingNewlines(generateModels(enriched, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateEnums(enums, ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(_ctx: EmitterContext): GeneratedFile[] {
    // Exception hierarchy is hand-maintained in workos-kotlin (see Phase 2).
    return [];
  },

  generateTypeSignatures(): GeneratedFile[] {
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateManifest(spec, ctx));
  },

  fileHeader(): string {
    return '// This file is auto-generated by oagen. Do not edit.';
  },

  formatCommand(): FormatCommand | null {
    // ktlint runs via `./gradlew ktlintFormat`; oagen does not invoke it per file.
    return null;
  },
};
