import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';
import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateTests } from './tests.js';
import { buildOperationsMap } from './manifest.js';
import { generateRbiFiles } from './rbi.js';
import { enrichModelsFromSpec, getSyntheticEnums } from '../shared/model-utils.js';

/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

/**
 * Flatten oneOf / allOf+oneOf variant fields onto each base model and pick
 * up the synthetic models / enums `enrichModelsFromSpec` produces for inline
 * variant shapes. Ruby emits flat hash-backed models, not sum types, so a
 * discriminated base whose IR fields were stripped (the new EventSchema-
 * style behaviour after the parser learned to walk allOf-wrapped variants)
 * has its original fields restored — otherwise `ConnectApplication`-style
 * bases would silently lose every variant field they had previously.
 */
function enrichModelsForRuby(models: Model[], enums: Enum[]): Model[] {
  const enriched = enrichModelsFromSpec(models, enums);
  const originalByName = new Map(models.map((m) => [m.name, m]));
  return enriched.map((m) => {
    if ((m as { discriminator?: unknown }).discriminator && m.fields.length === 0) {
      const original = originalByName.get(m.name);
      if (original && original.fields.length > 0) {
        return { ...m, fields: original.fields };
      }
    }
    return m;
  });
}

export const rubyEmitter: Emitter = {
  language: 'ruby',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    const modelFiles = generateModels(enrichModelsForRuby(models, ctx.spec.enums), ctx);
    return ensureTrailingNewlines(modelFiles);
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    const syntheticEnums = getSyntheticEnums();
    return ensureTrailingNewlines(generateEnums([...enums, ...syntheticEnums], ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(): GeneratedFile[] {
    // Hand-maintained in the target SDK — base_client.rb, errors.rb,
    // configuration.rb, hash_provider.rb, types/list_struct.rb,
    // test/test_helper.rb, and version.rb all carry `@oagen-ignore-file`
    // and are not regenerated.
    return [];
  },

  generateTypeSignatures(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    const rbiFiles = generateRbiFiles(spec, ctx);
    return ensureTrailingNewlines(rbiFiles);
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  buildOperationsMap(spec: ApiSpec, ctx: EmitterContext) {
    return buildOperationsMap(spec, ctx);
  },

  fileHeader(): string {
    return `# frozen_string_literal: true\n\n# This file is auto-generated by oagen. Do not edit.`;
  },

  formatCommand(targetDir: string): FormatCommand | null {
    void targetDir;
    // The WorkOS Ruby SDK uses standardrb. oagen appends the list of written
    // files as positional args after `args`; we filter to .rb files and pipe
    // them to `bundle exec standardrb --fix`. cwd is set to targetDir by the
    // harness so bundler picks up the SDK's Gemfile.
    //
    // Note: errors are NOT swallowed here — if standardrb fails (missing
    // bundle, syntax error, etc.) the engine surfaces it. Silence only hides
    // the fact that formatting never happened.
    return {
      cmd: 'bash',
      args: [
        '-c',
        'RB_FILES=$(for f in "$@"; do case "$f" in *.rb) echo "$f";; esac; done); ' +
          'if [ -n "$RB_FILES" ]; then printf "%s\\n" "$RB_FILES" | xargs bundle exec standardrb --fix --format quiet; fi',
        '--',
      ],
      batchSize: 1000,
    };
  },
};
