import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';
import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';
import { generateRbiFiles } from './rbi.js';

/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const rubyEmitter: Emitter = {
  language: 'ruby',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateModels(models, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateEnums(enums, ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(): GeneratedFile[] {
    // Hand-maintained in the target SDK — base_client.rb, errors.rb,
    // configuration.rb, hash_provider.rb, types/list_struct.rb,
    // test/test_helper.rb, and version.rb all carry `@oagen-ignore-file`
    // and are not regenerated.
    return [];
  },

  generateTypeSignatures(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateRbiFiles(spec, ctx));
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateManifest(spec, ctx));
  },

  fileHeader(): string {
    return '# This file is auto-generated by oagen. Do not edit.';
  },

  formatCommand(targetDir: string): FormatCommand | null {
    void targetDir;
    // The WorkOS Ruby SDK uses standardrb. oagen appends the list of written
    // files as positional args after `args`; we filter to .rb files and pipe
    // them to `bundle exec standardrb --fix`. cwd is set to targetDir by the
    // harness so bundler picks up the SDK's Gemfile.
    //
    // Note: errors are NOT swallowed here — if standardrb fails (missing
    // bundle, syntax error, etc.) the engine surfaces it. Silence only hides
    // the fact that formatting never happened.
    return {
      cmd: 'bash',
      args: [
        '-c',
        'RB_FILES=$(for f in "$@"; do case "$f" in *.rb) echo "$f";; esac; done); ' +
          'if [ -n "$RB_FILES" ]; then printf "%s\\n" "$RB_FILES" | xargs bundle exec standardrb --fix --format quiet; fi',
        '--',
      ],
      batchSize: 200,
    };
  },
};
