import type { Emitter, EmitterContext, GeneratedFile, ApiSpec, Model, Enum, Service } from '@workos/oagen';

import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateErrors } from './errors.js';
import { generateConfig } from './config.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';
import { initializeNaming, initializeEnumDedup } from './naming.js';

/** Initialize naming collision detection and enum deduplication from spec data. */
function ensureNamingInitialized(ctx: EmitterContext): void {
  const names = [...ctx.spec.models.map((m) => m.name), ...ctx.spec.enums.map((e) => e.name)];
  initializeNaming(names);
  initializeEnumDedup(ctx.spec.enums);
}

/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const phpEmitter: Emitter = {
  language: 'php',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    ensureNamingInitialized(ctx);
    return ensureTrailingNewlines(generateModels(models, ctx));
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    ensureNamingInitialized(ctx);
    return ensureTrailingNewlines(generateEnums(enums, ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    ensureNamingInitialized(ctx);
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    ensureNamingInitialized(ctx);
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(ctx: EmitterContext): GeneratedFile[] {
    ensureNamingInitialized(ctx);
    return ensureTrailingNewlines(generateErrors(ctx));
  },

  generateConfig(ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateConfig(ctx));
  },

  generateTypeSignatures(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    // PHP uses inline type hints — no separate type signature files needed
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    ensureNamingInitialized(ctx);
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    ensureNamingInitialized(ctx);
    return ensureTrailingNewlines(generateManifest(spec, ctx));
  },

  fileHeader(): string {
    return '<?php\ndeclare(strict_types=1);\n// This file is auto-generated by oagen. Do not edit.';
  },
};
