import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateSerializers } from './serializers.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateErrors } from './errors.js';
import { generateConfig } from './config.js';
import { generateCommon } from './common.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';

/** Ensure every generated file's content ends with a trailing newline. */
function ensureTrailingNewlines(files: GeneratedFile[]): GeneratedFile[] {
  for (const f of files) {
    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
  }
  return files;
}

export const nodeEmitter: Emitter = {
  language: 'node',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines([...generateModels(models, ctx), ...generateSerializers(models, ctx)]);
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateEnums(enums, ctx));
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateResources(services, ctx));
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateClient(spec, ctx));
  },

  generateErrors(ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateErrors(ctx));
  },

  generateConfig(_ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines([...generateConfig(), ...generateCommon()]);
  },

  generateTypeSignatures(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    // TypeScript uses inline types — no separate type signature files needed
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateTests(spec, ctx));
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return ensureTrailingNewlines(generateManifest(spec, ctx));
  },

  fileHeader(): string {
    return '// This file is auto-generated by oagen. Do not edit.';
  },

  formatCommand(targetDir: string): FormatCommand | null {
    const hasPrettier = fs.existsSync(path.join(targetDir, '.prettierrc'));
    const hasEslint =
      fs.existsSync(path.join(targetDir, 'eslint.config.mjs')) ||
      fs.existsSync(path.join(targetDir, 'eslint.config.js')) ||
      fs.existsSync(path.join(targetDir, '.eslintrc.json')) ||
      fs.existsSync(path.join(targetDir, '.eslintrc.js'));

    if (hasPrettier && hasEslint) {
      // Chain ESLint autofix (e.g. unused-import removal) then prettier.
      // ESLint errors are suppressed so formatting still runs on lint failure.
      return {
        cmd: 'bash',
        args: [
          '-c',
          'npx eslint --fix --no-error-on-unmatched-pattern "$@" 2>/dev/null; npx prettier --write --log-level silent "$@"',
          '--',
        ],
      };
    }
    if (hasPrettier) {
      return { cmd: 'npx', args: ['prettier', '--write', '--log-level', 'silent'] };
    }
    if (hasEslint) {
      return { cmd: 'npx', args: ['eslint', '--fix', '--no-error-on-unmatched-pattern'] };
    }
    return null;
  },
};
