import type {
  Emitter,
  EmitterContext,
  FormatCommand,
  GeneratedFile,
  ApiSpec,
  Model,
  Enum,
  Service,
} from '@workos/oagen';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { generateModelsAndSerializers } from './models.js';
import { generateEnums as generateEnumFiles } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { buildLiveSurface, emptyLiveSurface, setActiveLiveSurface, type LiveSurface } from './live-surface.js';
import { setBaselineSerializedNames, setBaselineInterfaceNames, resolveInterfaceName } from './naming.js';
import { setInlineEnumUnions, setDomainNameResolver } from './type-map.js';

/**
 * Cache live-surface per ctx — every emitter method receives the same ctx in
 * one oagen run, so we walk the target SDK once and reuse it.
 */
const surfaceCache = new WeakMap<EmitterContext, LiveSurface>();

function getSurface(ctx: EmitterContext): LiveSurface {
  let surface = surfaceCache.get(ctx);
  if (surface) return surface;
  // Prefer --output (where we are writing) over --target (rare for node).
  // The literal command `--output <SDK>` makes outputDir the SDK root.
  const root = ctx.outputDir ?? ctx.targetDir;
  surface = root ? buildLiveSurface(root) : emptyLiveSurface();
  surfaceCache.set(ctx, surface);
  setActiveLiveSurface(surface);

  // Wire the type-map's resolver so field-type references (`schema: X`) and
  // import statements (`import type { X }`) agree on the same name. The
  // structural baseline match in `resolveInterfaceName` can map an IR name
  // to a different live-SDK name (e.g. `AuditLogSchemaJson` → baseline
  // `AuditLogSchemaResponse` via `overlayLookup.modelNameByIR`).
  setDomainNameResolver((irName: string) => resolveInterfaceName(irName, ctx));

  // Tell `naming.wireInterfaceName` which `Serialized*` interfaces exist in
  // the live SDK so generated imports use the legacy name where applicable.
  // Source from the api-surface JSON (richer) when present, else fall back
  // to the disk walk.
  const serialized = new Set<string>();
  const ifaces = ctx.apiSurface?.interfaces;
  if (ifaces) {
    for (const name of Object.keys(ifaces)) {
      if (name.startsWith('Serialized')) serialized.add(name);
    }
  }
  for (const name of surface.interfaces.keys()) {
    if (name.startsWith('Serialized')) serialized.add(name);
  }
  setBaselineSerializedNames(serialized);

  // Full set of baseline interface names — used by `wireInterfaceName` to
  // detect when a `Response`-suffixed name has no `*Wire` companion in
  // the live SDK and is therefore the single-form wire interface.
  const allInterfaces = new Set<string>();
  if (ifaces) {
    for (const name of Object.keys(ifaces)) allInterfaces.add(name);
  }
  for (const name of surface.interfaces.keys()) allInterfaces.add(name);
  setBaselineInterfaceNames(allInterfaces);

  // Inline-enum optimization is intentionally disabled. workos-node emits the
  // dual `const X = {...} as const; type X = ...` pattern so callers can use
  // members at runtime (e.g. `GenerateLinkIntent.SSO`). Inlining the type
  // would drop the enum's file but leave value references in hand-written
  // test files dangling — see admin-portal.spec.ts referencing `.SSO`.
  // Pass an empty map; type-map will fall back to emitting the symbol name.
  setInlineEnumUnions(new Map());
  return surface;
}

/**
 * Apply the live-surface filter to a batch of generated files.
 *
 * Three signals decide what happens to each `GeneratedFile`:
 *
 *   1. `@oagen-ignore-file` marker (`surface.protectedFiles`) — the user has
 *      taken ownership of the file, never write on top of it.
 *   2. `auto-generated by oagen` header (`surface.autogenFiles`) — the file
 *      was produced by a prior generation. Spec changes (e.g. parameter
 *      renames) must propagate, so we leave the file in the output and let
 *      the engine's AST merger update it. No skip flags.
 *   3. File on disk without either marker — treat as hand-written; drop from
 *      the output to avoid the engine prepending a header on `skipIfExists`
 *      files (see writeFiles:~4360 in @workos/oagen) or merging unrequested
 *      changes into it.
 *   4. Brand-new path in an existing SDK — drop it. For a live SDK we treat
 *      the git-tracked baseline as the managed surface; generating new files
 *      is what caused the workos-node file explosion.
 *
 * `integrateTarget: false` files (smoke-manifest.json etc.) are also dropped:
 * with no `--target` step they would otherwise land as untracked cruft.
 *
 * Note: pairing this with `--no-prune` is required for stable behavior — see
 * `scripts/sdk-generate.sh` in the spec repo, which enables it for `--lang node`.
 */
/**
 * `*.spec.ts`, `*.test.ts`, and JSON fixtures under `fixtures/` are owned by
 * the test author after first emission. The emitter scaffolds them on a
 * brand-new resource, but subsequent regenerations must leave them alone —
 * assertions get hand-tuned, fixture data gets stabilized, and re-emission
 * would point them at sibling serializers/interfaces that may have shape-
 * shifted under the user's feet.
 */
function isUserOwnedAfterFirstEmit(relPath: string): boolean {
  if (relPath.endsWith('.spec.ts') || relPath.endsWith('.test.ts')) return true;
  if (/\/fixtures\/[^/]+\.json$/.test(relPath)) return true;
  return false;
}

function applyLiveSurface(files: GeneratedFile[], surface: LiveSurface): GeneratedFile[] {
  const out: GeneratedFile[] = [];
  const managedPaths = surface.trackedFiles.size > 0 ? surface.trackedFiles : surface.files;
  const hasExistingSdk = managedPaths.size > 0;
  for (const f of files) {
    if (f.integrateTarget === false) continue;
    if (surface.protectedFiles.has(f.path)) continue;
    if (hasExistingSdk && !managedPaths.has(f.path)) continue;

    // Hand-written files (on disk, no `auto-generated by oagen` header) →
    // drop. The engine would otherwise prepend the header on
    // `skipIfExists: true` files (writeFiles:~4360), and the merger may
    // try to splice generated symbols into hand-written ones.
    if (surface.files.has(f.path) && !surface.autogenFiles.has(f.path)) continue;

    // Test specs and fixtures: author-owned after first emission. Once a
    // test file or fixture exists on disk, the user owns it — the emitter
    // re-emitting against new IR would either replace assertions/data the
    // user has hand-tuned, or leave it pointing at sibling files that no
    // longer have the same shape. Treat existing test/fixture files as
    // frozen even when they carry the auto-gen header.
    if (surface.files.has(f.path) && isUserOwnedAfterFirstEmit(f.path)) {
      continue;
    }

    // Previously auto-generated files → fully overwrite so spec changes
    // (e.g. parameter renames like `admin_emails` → `it_contact_emails`)
    // propagate. The engine's default AST merger is additive and would
    // leave the old name on existing methods. Files marked
    // `@oagen-ignore-start`/`@oagen-ignore-end` regions inside the file
    // are still preserved by `overwriteWithPreservedRegions` in the
    // engine.
    if (surface.autogenFiles.has(f.path)) {
      f.overwriteExisting = true;
      f.skipIfExists = false;
    }

    if (f.content && !f.content.endsWith('\n')) {
      f.content += '\n';
    }
    out.push(f);
  }
  return out;
}

export const nodeEmitter: Emitter = {
  language: 'node',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    const surface = getSurface(ctx);
    return applyLiveSurface(generateModelsAndSerializers(models, ctx), surface);
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    const surface = getSurface(ctx);
    return applyLiveSurface(generateEnumFiles(enums, ctx), surface);
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    const surface = getSurface(ctx);
    return applyLiveSurface(generateResources(services, ctx), surface);
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    const surface = getSurface(ctx);
    return applyLiveSurface(generateClient(spec, ctx), surface);
  },

  // workos-node ships its own exception hierarchy under src/common/exceptions/.
  // Re-emitting them would either skip (if files exist) or overwrite hand-edits.
  generateErrors(_ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateTypeSignatures(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  // Test specs and fixtures are hand-maintained per workos-node convention.
  // We do not regenerate them.
  generateTests(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  // No operations map needed — the manifest belongs to the staging+target flow,
  // which the literal `--output <SDK>` command does not use.
  buildOperationsMap(): Record<string, never> {
    return {};
  },

  fileHeader(): string {
    return '// This file is auto-generated by oagen. Do not edit.';
  },

  formatCommand(targetDir: string): FormatCommand | null {
    const hasPrettier = fs.existsSync(path.join(targetDir, '.prettierrc'));
    const hasEslint =
      fs.existsSync(path.join(targetDir, 'eslint.config.mjs')) ||
      fs.existsSync(path.join(targetDir, 'eslint.config.js')) ||
      fs.existsSync(path.join(targetDir, '.eslintrc.json')) ||
      fs.existsSync(path.join(targetDir, '.eslintrc.js'));

    if (hasPrettier && hasEslint) {
      return {
        cmd: 'bash',
        args: [
          '-c',
          'npx eslint --fix --no-error-on-unmatched-pattern "$@" 2>/dev/null; npx prettier --write --log-level silent "$@"',
          '--',
        ],
      };
    }
    if (hasPrettier) {
      return {
        cmd: 'npx',
        args: ['prettier', '--write', '--log-level', 'silent'],
      };
    }
    if (hasEslint) {
      return {
        cmd: 'npx',
        args: ['eslint', '--fix', '--no-error-on-unmatched-pattern'],
      };
    }
    return null;
  },
};
