import type { Emitter, EmitterContext, GeneratedFile, ApiSpec, Model, Enum, Service } from '@workos/oagen';
import { IR_VERSION } from '@workos/oagen';
import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateSerializers } from './serializers.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateErrors } from './errors.js';
import { generateConfig } from './config.js';
import { generateCommon } from './common.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';

export const nodeEmitter: Emitter = {
  language: 'node',
  contractVersion: IR_VERSION,

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    return [...generateModels(models, ctx), ...generateSerializers(models, ctx)];
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return generateEnums(enums, ctx);
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return generateResources(services, ctx);
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateClient(spec, ctx);
  },

  generateErrors(_ctx: EmitterContext): GeneratedFile[] {
    return generateErrors();
  },

  generateConfig(_ctx: EmitterContext): GeneratedFile[] {
    return [...generateConfig(), ...generateCommon()];
  },

  generateTypeSignatures(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    // TypeScript uses inline types — no separate type signature files needed
    return [];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateTests(spec, ctx);
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateManifest(spec, ctx);
  },

  fileHeader(): string {
    return '// This file is auto-generated by oagen. Do not edit.';
  },
};
