import * as fs from 'node:fs';
import * as path from 'node:path';
import { execFileSync } from 'node:child_process';

/**
 * Snapshot of the live target SDK gathered by walking `--output` once.
 *
 * Replaces the heavier `--api-surface` extract step for the Node emitter.
 * Only declaration *names* are extracted (regex-based, no AST). That is
 * enough to drive "skip if already present" filtering in models, resources,
 * and serializers.
 */
export interface LiveSurface {
  /** Absolute root the surface was built from (e.g. workos-node repo root). */
  rootDir: string;
  /** Set of file paths (relative to rootDir, POSIX separators) that exist on disk. */
  files: Set<string>;
  /**
   * Git-tracked paths under the SDK root.
   *
   * When non-empty, this is the canonical baseline surface for "existing SDK"
   * decisions. It excludes prior bad generations that left untracked files in
   * the tree, which lets the emitter stop re-emitting that junk so manifest
   * pruning can clean it up on the next run.
   */
  trackedFiles: Set<string>;
  /** Files marked `@oagen-ignore-file`: never emit on top of these. */
  protectedFiles: Set<string>;
  /**
   * Files whose first lines contain the `auto-generated by oagen` header.
   * These were produced by a prior generation and should be regenerated when
   * the spec changes (e.g. parameter renames). Letting the engine see them
   * in the new output list is what enables that update path — dropping them
   * would freeze them at their last-generated content.
   */
  autogenFiles: Set<string>;
  /** Class name → relative file path. */
  classes: Map<string, ClassInfo>;
  /** Interface or type-alias name → relative file path. */
  interfaces: Map<string, InterfaceInfo>;
  /** Function name → relative file path (for serializers, helpers). */
  functions: Map<string, string>;
  /**
   * `export const X = {...} as const` declarations on disk → ordered
   * member-name → literal-value mapping. Used by `enums.ts` to preserve
   * acronym casing (e.g. `DSync: 'dsync'`) on regeneration; without this,
   * `toPascalCase('dsync')` would emit `Dsync` and silently break call
   * sites that referenced `EnumName.DSync`.
   */
  constObjectEnums: Map<string, Map<string, string>>;
}

export interface ClassInfo {
  filePath: string;
  methods: Set<string>;
}

export interface InterfaceInfo {
  filePath: string;
  fields: Set<string>;
}

const SRC_DIR = 'src';

/**
 * Walk `${rootDir}/src/` and build a live-surface snapshot.
 *
 * If `${rootDir}/src/` does not exist, returns an empty surface (greenfield).
 * Reads each `.ts` file once; ignores `.spec.ts` and `.test.ts`.
 */
export function buildLiveSurface(rootDir: string): LiveSurface {
  const surface: LiveSurface = {
    rootDir,
    files: new Set(),
    trackedFiles: loadGitTrackedFiles(rootDir),
    protectedFiles: new Set(),
    autogenFiles: new Set(),
    classes: new Map(),
    interfaces: new Map(),
    functions: new Map(),
    constObjectEnums: new Map(),
  };

  const srcRoot = path.join(rootDir, SRC_DIR);
  if (!fs.existsSync(srcRoot) || !fs.statSync(srcRoot).isDirectory()) {
    return surface;
  }

  for (const absPath of walk(srcRoot)) {
    const rel = toPosix(path.relative(rootDir, absPath));
    surface.files.add(rel);
    if (!rel.endsWith('.ts')) continue;
    if (surface.trackedFiles.size > 0 && !surface.trackedFiles.has(rel)) continue;

    let text: string;
    try {
      text = fs.readFileSync(absPath, 'utf8');
    } catch {
      continue;
    }

    if (isProtected(text)) {
      surface.protectedFiles.add(rel);
    } else if (isAutogen(text)) {
      surface.autogenFiles.add(rel);
    }

    if (rel.endsWith('.spec.ts') || rel.endsWith('.test.ts')) continue;

    extractDeclarations(text, rel, surface);
  }

  return surface;
}

/**
 * Module-level snapshot of the active live-surface, set by `index.ts` once per
 * generation run. Used by callers that don't have a clean way to thread
 * `EmitterContext` through (e.g. deeply-nested helpers in `resources.ts`
 * that decide whether to inline a serializer call).
 */
let activeSurface: LiveSurface | null = null;
export function setActiveLiveSurface(surface: LiveSurface): void {
  activeSurface = surface;
}
export function liveSurfaceHasFunction(name: string): boolean {
  return activeSurface?.functions.has(name) ?? false;
}
/** Returns the relative file path containing the function, if known. */
export function liveSurfaceFunctionPath(name: string): string | undefined {
  return activeSurface?.functions.get(name);
}
export function liveSurfaceHasFile(relPath: string): boolean {
  return activeSurface?.files.has(relPath) ?? false;
}
export function liveSurfaceHasManagedFile(relPath: string): boolean {
  const surface = activeSurface;
  if (!surface) return false;
  const managedPaths = surface.trackedFiles.size > 0 ? surface.trackedFiles : surface.files;
  return managedPaths.has(relPath);
}
export function liveSurfaceHasAutogenFile(relPath: string): boolean {
  return activeSurface?.autogenFiles.has(relPath) ?? false;
}
export function liveSurfaceHasExistingSdk(): boolean {
  const surface = activeSurface;
  if (!surface) return false;
  const managedPaths = surface.trackedFiles.size > 0 ? surface.trackedFiles : surface.files;
  return managedPaths.size > 0;
}

/** Empty surface — used as a default when no outputDir is available. */
export function emptyLiveSurface(): LiveSurface {
  return {
    rootDir: '',
    files: new Set(),
    trackedFiles: new Set(),
    protectedFiles: new Set(),
    autogenFiles: new Set(),
    classes: new Map(),
    interfaces: new Map(),
    functions: new Map(),
    constObjectEnums: new Map(),
  };
}

/** Returns the existing member-name → value map for a const-object enum, if any. */
export function liveSurfaceConstEnumMembers(name: string): Map<string, string> | undefined {
  return activeSurface?.constObjectEnums.get(name);
}
export function liveSurfaceInterfacePath(name: string): string | undefined {
  return activeSurface?.interfaces.get(name)?.filePath;
}

/** Should the emitter avoid writing this relative path on disk? */
export function shouldSkipPath(surface: LiveSurface, relPath: string): boolean {
  return surface.protectedFiles.has(relPath);
}

/** Does the live SDK already contain a file at this relative path? */
export function pathExists(surface: LiveSurface, relPath: string): boolean {
  return surface.files.has(relPath);
}

function* walk(dir: string): Generator<string> {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      yield* walk(abs);
    } else if (entry.isFile()) {
      yield abs;
    }
  }
}

function toPosix(p: string): string {
  return p.split(path.sep).join('/');
}

function loadGitTrackedFiles(rootDir: string): Set<string> {
  try {
    const stdout = execFileSync('git', ['-C', rootDir, 'ls-files', '--', 'src'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return new Set(
      stdout
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter(Boolean)
        .map(toPosix),
    );
  } catch {
    return new Set();
  }
}

function isProtected(text: string): boolean {
  // Look in the first 800 chars only — markers belong at file top.
  const head = text.slice(0, 800);
  return /@oagen-ignore-file\b/.test(head);
}

function isAutogen(text: string): boolean {
  // Same locality assumption — the auto-generated header is always at top.
  const head = text.slice(0, 400);
  return /auto-generated by oagen/i.test(head);
}

const CLASS_RE = /^\s*export\s+(?:abstract\s+)?class\s+([A-Z][\w$]*)/gm;
const INTERFACE_RE = /^\s*export\s+interface\s+([A-Z][\w$]*)/gm;
const TYPE_ALIAS_RE = /^\s*export\s+type\s+([A-Z][\w$]*)\s*=/gm;
// Picks up both standard declarations (`export function deserializeX(...)`)
// and arrow-style consts (`export const deserializeX = (...) =>`). The
// latter is the workos-node house style for serializers, including the
// generic-arrow form `export const deserializeProfile = <T extends ...>(`.
const FUNCTION_RE = /^\s*export\s+(?:async\s+)?function\s+([a-zA-Z_$][\w$]*)/gm;
const CONST_FN_RE = /^\s*export\s+const\s+([a-zA-Z_$][\w$]*)\s*(?::\s*[^=]+)?=\s*(?:async\s+)?(?:<[^>]*>\s*)?\(/gm;
// For methods, match a class member declaration (rough — picks up async + plain methods).
const METHOD_RE =
  /^\s{2,}(?:public\s+|private\s+|protected\s+|readonly\s+)*(?:async\s+)?([a-zA-Z_$][\w$]*)\s*(?:<[^>]*>)?\s*\(/gm;

function extractDeclarations(text: string, relPath: string, surface: LiveSurface): void {
  // Classes
  for (const m of text.matchAll(CLASS_RE)) {
    const name = m[1];
    const body = sliceClassBody(text, m.index ?? 0);
    const methods = new Set<string>();
    if (body) {
      for (const mm of body.matchAll(METHOD_RE)) {
        const methodName = mm[1];
        // Filter out keywords accidentally captured.
        if (METHOD_KEYWORD_BLOCKLIST.has(methodName)) continue;
        methods.add(methodName);
      }
    }
    surface.classes.set(name, { filePath: relPath, methods });
  }

  // Interfaces
  for (const m of text.matchAll(INTERFACE_RE)) {
    const name = m[1];
    const fields = extractInterfaceFields(text, m.index ?? 0);
    surface.interfaces.set(name, { filePath: relPath, fields });
  }

  // Type aliases (treated as interfaces for skip purposes; field set is empty).
  for (const m of text.matchAll(TYPE_ALIAS_RE)) {
    const name = m[1];
    if (!surface.interfaces.has(name)) {
      surface.interfaces.set(name, { filePath: relPath, fields: new Set() });
    }
  }

  // Top-level exported functions (both `function` and arrow-const styles).
  for (const m of text.matchAll(FUNCTION_RE)) {
    surface.functions.set(m[1], relPath);
  }
  for (const m of text.matchAll(CONST_FN_RE)) {
    surface.functions.set(m[1], relPath);
  }

  // `export const X = { Member: 'value', ... } as const;` — capture the
  // member-name → literal-value mapping so enum regeneration can preserve
  // existing casing (e.g. `DSync: 'dsync'` instead of `Dsync: 'dsync'`).
  for (const m of text.matchAll(CONST_OBJECT_ENUM_RE)) {
    const enumName = m[1];
    const body = m[2];
    const members = new Map<string, string>();
    for (const memberMatch of body.matchAll(CONST_OBJECT_MEMBER_RE)) {
      const memberName = memberMatch[1] ?? memberMatch[2] ?? memberMatch[3];
      const value = memberMatch[4];
      if (memberName && value !== undefined) {
        members.set(value, memberName);
      }
    }
    if (members.size > 0) {
      surface.constObjectEnums.set(enumName, members);
    }
  }
}

// `export const X = { ... } as const`
const CONST_OBJECT_ENUM_RE = /^\s*export\s+const\s+([A-Z][\w$]*)\s*=\s*\{([\s\S]*?)\}\s*as\s+const\s*;/gm;
// Member entries inside the object body — supports unquoted, single-quoted,
// and double-quoted keys. Captures key (group 1/2/3) → string value (group 4).
const CONST_OBJECT_MEMBER_RE = /(?:'([^']+)'|"([^"]+)"|([a-zA-Z_$][\w$]*))\s*:\s*'([^']*)'/g;

const METHOD_KEYWORD_BLOCKLIST = new Set([
  'if',
  'for',
  'while',
  'switch',
  'catch',
  'return',
  'throw',
  'constructor', // tracked separately if needed
]);

// ---------------------------------------------------------------------------
// Partial-emission merge
//
// For a service that is NOT owned and NOT a missing-service adoption,
// `resources.ts` intentionally emits a PARTIAL resource class: operations
// already covered by the baseline class are filtered out, leaving only the
// new methods. Overwriting the on-disk file with that partial class would
// delete every existing public method (this deleted four methods from
// workos-node's api-keys.ts when the spec gained one operation). The helpers
// below let `applyLiveSurface` detect that case and merge instead: keep the
// existing file text verbatim and append only the generated-only methods
// (plus any imports they need).
// ---------------------------------------------------------------------------

interface ParsedClassLines {
  name: string;
  /** Line index of the `export class` declaration. */
  declLine: number;
  /** Line index of the line containing the class body's closing brace. */
  closeLine: number;
  /** Method names declared directly on the class body, in source order. */
  methods: string[];
}

// Class members sit at exactly two-space indent in both generated output and
// prettier-formatted SDK files; deeper-indented lines are method bodies.
const CLASS_MEMBER_RE =
  /^ {2}(?:(?:public|private|protected|readonly|static)\s+)*(?:async\s+)?([a-zA-Z_$][\w$]*)\s*(?:<[^>]*>)?\s*\(/;

function parseClassesByLine(lines: string[]): ParsedClassLines[] {
  const classes: ParsedClassLines[] = [];
  for (let i = 0; i < lines.length; i++) {
    const decl = lines[i].match(/^export\s+(?:abstract\s+)?class\s+([A-Z][\w$]*)/);
    if (!decl) continue;

    let depth = 0;
    let started = false;
    let closeLine = -1;
    for (let j = i; j < lines.length && closeLine < 0; j++) {
      for (const ch of lines[j]) {
        if (ch === '{') {
          depth++;
          started = true;
        } else if (ch === '}') {
          depth--;
          if (started && depth === 0) {
            closeLine = j;
            break;
          }
        }
      }
    }
    if (closeLine < 0) continue;

    const methods: string[] = [];
    for (let j = i + 1; j < closeLine; j++) {
      const member = lines[j].match(CLASS_MEMBER_RE);
      if (!member) continue;
      const name = member[1];
      if (name === 'constructor' || METHOD_KEYWORD_BLOCKLIST.has(name)) continue;
      if (!methods.includes(name)) methods.push(name);
    }
    classes.push({ name: decl[1], declLine: i, closeLine, methods });
    i = closeLine;
  }
  return classes;
}

/**
 * Extract the full source block of `method` (attached comments included) from
 * a parsed class. Returns null if the block cannot be delimited.
 */
function extractMethodBlock(lines: string[], cls: ParsedClassLines, method: string): string[] | null {
  for (let j = cls.declLine + 1; j < cls.closeLine; j++) {
    const member = lines[j].match(CLASS_MEMBER_RE);
    if (!member || member[1] !== method) continue;

    // Pull in the contiguous comment block directly above the signature.
    let start = j;
    while (start > cls.declLine + 1) {
      const above = lines[start - 1].trim();
      if (above.startsWith('//') || above.startsWith('/*') || above.startsWith('*')) start--;
      else break;
    }

    // The member ends at the first two-space-indented closing brace.
    for (let end = j; end < cls.closeLine; end++) {
      if (/^ {2}\}[,;]?\s*$/.test(lines[end])) {
        return lines.slice(start, end + 1);
      }
    }
    return null;
  }
  return null;
}

// Multi-line tolerant: prettier wraps long named-import lists across lines.
const IMPORT_STMT_RE =
  /^import\s+(type\s+)?(?:([A-Za-z_$][\w$]*)\s*,?\s*)?(?:\{([\s\S]*?)\}\s*)?(?:\*\s+as\s+([A-Za-z_$][\w$]*)\s+)?from\s+['"]([^'"]+)['"];?/gm;

function importLocalName(entry: string): string {
  const asMatch = entry.match(/\s+as\s+([A-Za-z_$][\w$]*)\s*$/);
  if (asMatch) return asMatch[1];
  return entry.replace(/^type\s+/, '').trim();
}

function collectImportedLocalNames(text: string): Set<string> {
  const names = new Set<string>();
  for (const m of text.matchAll(IMPORT_STMT_RE)) {
    if (m[2]) names.add(m[2]);
    if (m[4]) names.add(m[4]);
    for (const entry of (m[3] ?? '').split(',')) {
      const trimmed = entry.trim();
      if (trimmed) names.add(importLocalName(trimmed));
    }
  }
  return names;
}

/** Import statements from `generatedText` whose names `existingText` lacks. */
function missingImportStatements(existingText: string, generatedText: string): string[] {
  const existingNames = collectImportedLocalNames(existingText);
  const statements: string[] = [];
  for (const m of generatedText.matchAll(IMPORT_STMT_RE)) {
    const [stmt, typeOnly, defaultName, named, namespaceName, moduleSpec] = m;
    if (defaultName || namespaceName) {
      // Default/namespace imports: append verbatim when the local is missing.
      const local = defaultName ?? namespaceName;
      if (local && !existingNames.has(local)) statements.push(stmt.endsWith(';') ? stmt : `${stmt};`);
      continue;
    }
    const missing = (named ?? '')
      .split(',')
      .map((entry) => entry.trim())
      .filter((entry) => entry && !existingNames.has(importLocalName(entry)));
    if (missing.length === 0) continue;
    statements.push(`import ${typeOnly ? 'type ' : ''}{ ${missing.join(', ')} } from '${moduleSpec}';`);
  }
  return statements;
}

/**
 * Merge a partial class emission into the existing on-disk file content.
 *
 * Acts only when a class declared in BOTH texts has methods on disk that the
 * generated content drops — the signature of a "new operations only" partial
 * emission. Returns the existing text with the generated-only methods appended
 * to the class body (and missing imports added), preserving every existing
 * method and import verbatim.
 *
 * Returns null when the generated content does not drop any existing method;
 * callers should then proceed with their normal (overwrite) path so full
 * regenerations keep propagating emitter improvements and spec renames.
 */
export function mergeGeneratedClassMethodsIntoExisting(existingText: string, generatedText: string): string | null {
  const existingLines = existingText.split('\n');
  const generatedLines = generatedText.split('\n');
  const existingClasses = parseClassesByLine(existingLines);
  if (existingClasses.length === 0) return null;
  const generatedClasses = new Map(parseClassesByLine(generatedLines).map((cls) => [cls.name, cls]));

  let dropsExistingMethod = false;
  const insertions: Array<{ atLine: number; blocks: string[][] }> = [];
  for (const existing of existingClasses) {
    const generated = generatedClasses.get(existing.name);
    if (!generated) continue;
    const generatedMethods = new Set(generated.methods);
    if (!existing.methods.some((method) => !generatedMethods.has(method))) continue;
    dropsExistingMethod = true;

    const existingMethods = new Set(existing.methods);
    const blocks: string[][] = [];
    for (const method of generated.methods) {
      if (existingMethods.has(method)) continue;
      const block = extractMethodBlock(generatedLines, generated, method);
      if (block) blocks.push(block);
    }
    if (blocks.length > 0) insertions.push({ atLine: existing.closeLine, blocks });
  }
  if (!dropsExistingMethod) return null;

  const merged = [...existingLines];
  // Bottom-up so earlier insertions don't shift later line indices. Imports
  // sit above every class body, so the import insertion point (computed on
  // the original text) stays valid after these splices.
  insertions.sort((a, b) => b.atLine - a.atLine);
  for (const insertion of insertions) {
    const blockLines: string[] = [];
    for (const block of insertion.blocks) {
      blockLines.push('', ...block);
    }
    merged.splice(insertion.atLine, 0, ...blockLines);
  }

  const importStatements = missingImportStatements(existingText, generatedText);
  if (importStatements.length > 0) {
    let lastImportLine = -1;
    for (let i = 0; i < existingLines.length; i++) {
      if (
        /from\s+['"][^'"]+['"];?\s*$/.test(existingLines[i]) ||
        /^import\s+['"][^'"]+['"];?\s*$/.test(existingLines[i])
      ) {
        lastImportLine = i;
      }
    }
    if (lastImportLine >= 0) {
      merged.splice(lastImportLine + 1, 0, ...importStatements);
    } else {
      // No imports yet: place them after the leading comment block.
      let insertAt = 0;
      while (insertAt < existingLines.length) {
        const line = existingLines[insertAt].trim();
        if (line === '' || line.startsWith('//') || line.startsWith('/*') || line.startsWith('*')) insertAt++;
        else break;
      }
      merged.splice(insertAt, 0, ...importStatements, '');
    }
  }

  return merged.join('\n');
}

/**
 * Given the start index of a class declaration, return the brace-delimited body
 * as a substring. Returns '' if the body cannot be located.
 */
function sliceClassBody(text: string, start: number): string {
  const open = text.indexOf('{', start);
  if (open < 0) return '';
  let depth = 0;
  for (let i = open; i < text.length; i++) {
    const c = text[i];
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) {
        return text.slice(open + 1, i);
      }
    }
  }
  return '';
}

/**
 * Pull field names from an interface body. Conservative: only matches simple
 * declarations of the form `name?: ...;` or `name: ...;`. Generics, methods,
 * and computed property names are skipped (they don't influence skip decisions).
 */
function extractInterfaceFields(text: string, start: number): Set<string> {
  const fields = new Set<string>();
  const open = text.indexOf('{', start);
  if (open < 0) return fields;
  let depth = 0;
  let close = -1;
  for (let i = open; i < text.length; i++) {
    const c = text[i];
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) {
        close = i;
        break;
      }
    }
  }
  if (close < 0) return fields;
  const body = text.slice(open + 1, close);
  const fieldRe = /^\s*(?:readonly\s+)?(?:'([^']+)'|"([^"]+)"|([a-zA-Z_$][\w$]*))\s*\??\s*:/gm;
  for (const m of body.matchAll(fieldRe)) {
    const name = m[1] ?? m[2] ?? m[3];
    if (name) fields.add(name);
  }
  return fields;
}
