import type { EmitterContext } from '@workos/oagen';

export interface OperationOverride {
  methodName?: string;
  mountOn?: string;
  optionsType?: string;
  bodyFieldMap?: Record<string, string>;
  returnType?: string;
  returnDataProperty?: string;
  returnTypeImports?: string[];
  returnExpression?: string;
}

export interface NodeEmitterOptions {
  /**
   * Existing SDK mode normally drops brand-new paths to avoid large accidental
   * generations. When enabled, brand-new top-level service directories whose
   * services are absent from the SDK are adopted from the spec.
   */
  adoptMissingServices?: boolean;
  /**
   * Existing tracked service directories to move under oagen ownership.
   *
   * Entries may be IR service names or resolved resource class names
   * (for example, "Groups"). Owned service files are allowed to overwrite
   * tracked, non-autogenerated files so the service can be migrated into the
   * manifest one service at a time.
   */
  ownedServices?: string[];
  /**
   * Regenerate tests and fixtures for owned services. Non-owned service tests
   * and fixtures remain hand-owned.
   */
  regenerateOwnedTests?: boolean;
  /**
   * Node-specific operation overrides keyed by "METHOD /path".
   * Allows renaming methods or remounting operations for the Node SDK
   * without affecting other languages.
   */
  operationOverrides?: Record<string, OperationOverride>;
  /**
   * Type/model names whose hand-written declarations are authoritative even
   * inside an owned service. The emitter will NOT generate an interface or
   * serializer for these names; instead it treats them like a baseline type,
   * routing imports and barrel exports to the existing hand-written file.
   *
   * Use this to keep hand-owned generics the OpenAPI spec cannot express
   * (for example `DirectoryUserWithGroups<TCustomAttributes>`) while still
   * letting oagen own the rest of the service.
   */
  handOwnedTypes?: string[];
}

export function nodeOptions(ctx: EmitterContext): NodeEmitterOptions {
  return ((ctx as EmitterContext & { emitterOptions?: Record<string, unknown> }).emitterOptions ??
    {}) as NodeEmitterOptions;
}

function normalizeServiceName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
}

function ownedLookupNames(name: string): string[] {
  const names = [name];
  const baselineDirPrefix = '__baseline_dir__:';
  if (name.startsWith(baselineDirPrefix)) {
    names.push(name.slice(baselineDirPrefix.length));
  }
  return names;
}

export function isNodeOwnedService(ctx: EmitterContext, ...names: Array<string | undefined>): boolean {
  const configured = nodeOptions(ctx).ownedServices ?? [];
  if (configured.length === 0) return false;

  const owned = new Set(configured.map(normalizeServiceName));
  return names.some((name) =>
    name !== undefined ? ownedLookupNames(name).some((candidate) => owned.has(normalizeServiceName(candidate))) : false,
  );
}

/**
 * True when `name` is a hand-owned type (see {@link NodeEmitterOptions.handOwnedTypes}).
 * Hand-owned types are never generated; the emitter defers to the existing
 * hand-written declaration and routes imports/barrel exports to it.
 */
export function isHandOwnedType(ctx: EmitterContext, name: string | undefined): boolean {
  if (name === undefined) return false;
  const configured = nodeOptions(ctx).handOwnedTypes;
  if (!configured || configured.length === 0) return false;
  return configured.includes(name);
}
