import type { EmitterContext } from '@workos/oagen';

export interface NodeEmitterOptions {
  /**
   * Existing SDK mode normally drops brand-new paths to avoid large accidental
   * generations. When enabled, brand-new top-level service directories whose
   * services are absent from the SDK are adopted from the spec.
   */
  adoptMissingServices?: boolean;
  /**
   * Existing tracked service directories to move under oagen ownership.
   *
   * Entries may be IR service names or resolved resource class names
   * (for example, "Groups"). Owned service files are allowed to overwrite
   * tracked, non-autogenerated files so the service can be migrated into the
   * manifest one service at a time.
   */
  ownedServices?: string[];
  /**
   * Regenerate tests and fixtures for owned services. Non-owned service tests
   * and fixtures remain hand-owned.
   */
  regenerateOwnedTests?: boolean;
}

export function nodeOptions(ctx: EmitterContext): NodeEmitterOptions {
  return ((ctx as EmitterContext & { emitterOptions?: Record<string, unknown> }).emitterOptions ??
    {}) as NodeEmitterOptions;
}

function normalizeServiceName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
}

export function isNodeOwnedService(ctx: EmitterContext, ...names: Array<string | undefined>): boolean {
  const configured = nodeOptions(ctx).ownedServices ?? [];
  if (configured.length === 0) return false;

  const owned = new Set(configured.map(normalizeServiceName));
  return names.some((name) => name !== undefined && owned.has(normalizeServiceName(name)));
}
