import type { EmitterContext, Operation, OperationPlan } from '@workos/oagen';
import { planOperation } from '@workos/oagen';

export interface OperationOverride {
  methodName?: string;
  mountOn?: string;
  optionsType?: string;
  bodyFieldMap?: Record<string, string>;
  /**
   * Rename spec path parameters to the SDK options-object field they should be
   * exposed as. Keys are the camelCase identifier the param resolves to via
   * `fieldName(param.name)` — NOT the raw (possibly snake_case) spec key — since
   * the lookup is keyed on that camelCase form (e.g. `{ resourceId: 'targetId' }`,
   * even for a `resource_id` spec param). Applied to the destructure, the URL
   * template binding, and generated tests so a published SDK field name can
   * diverge from the spec path-param name without a global spec rewrite (which
   * would ripple across every language).
   */
  pathFieldMap?: Record<string, string>;
  returnType?: string;
  returnDataProperty?: string;
  returnTypeImports?: string[];
  returnExpression?: string;
  /**
   * Override the response model the operation deserializes, by model name.
   * Replaces the spec-derived response model so the resource (and its test)
   * reference a different wire type / deserializer — e.g. mapping
   * Authorization's role responses to the full `OrganizationRole` instead of
   * the slim `Role`/`RoleResponse` shape shared with SSO and UserManagement.
   * Node-only; never affects the global spec or other SDKs.
   */
  responseModel?: string;
}

export interface NodeEmitterOptions {
  /**
   * Existing SDK mode normally drops brand-new paths to avoid large accidental
   * generations. When enabled, brand-new top-level service directories whose
   * services are absent from the SDK are adopted from the spec.
   */
  adoptMissingServices?: boolean;
  /**
   * Existing tracked service directories to move under oagen ownership.
   *
   * Entries may be IR service names or resolved resource class names
   * (for example, "Groups"). Owned service files are allowed to overwrite
   * tracked, non-autogenerated files so the service can be migrated into the
   * manifest one service at a time.
   */
  ownedServices?: string[];
  /**
   * Regenerate tests and fixtures for owned services. Non-owned service tests
   * and fixtures remain hand-owned.
   */
  regenerateOwnedTests?: boolean;
  /**
   * Node-specific operation overrides keyed by "METHOD /path".
   * Allows renaming methods or remounting operations for the Node SDK
   * without affecting other languages.
   */
  operationOverrides?: Record<string, OperationOverride>;
  /**
   * Type/model names whose hand-written declarations are authoritative even
   * inside an owned service. The emitter will NOT generate an interface or
   * serializer for these names; instead it treats them like a baseline type,
   * routing imports and barrel exports to the existing hand-written file.
   *
   * Use this to keep hand-owned generics the OpenAPI spec cannot express
   * (for example `DirectoryUserWithGroups<TCustomAttributes>`) while still
   * letting oagen own the rest of the service.
   */
  handOwnedTypes?: string[];
  /**
   * Remap an enum's raw wire string values to different SDK-facing (domain)
   * values, keyed by enum name then `{ wireValue: domainValue }`.
   *
   * The OpenAPI spec can only describe the raw wire enum, but some SDK surfaces
   * have historically presented translated values (e.g. WorkOS directory state
   * `linked`/`unlinked` surfaced as `active`/`inactive`). Configuring a remap
   * makes the emitter generate, for that enum:
   *   - a domain type with the mapped values (`DirectoryState`),
   *   - a wire type with the raw values (`DirectoryStateResponse`),
   *   - a `deserialize<Enum>` mapper that converts wire → domain, and
   *   - generated tests that assert the domain value.
   * Wire values absent from the map pass through unchanged. Node-only; never
   * affects the global spec or other SDKs.
   */
  enumValueRemaps?: Record<string, Record<string, string>>;
}

export function nodeOptions(ctx: EmitterContext): NodeEmitterOptions {
  return ((ctx as EmitterContext & { emitterOptions?: Record<string, unknown> }).emitterOptions ??
    {}) as NodeEmitterOptions;
}

function normalizeServiceName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
}

function ownedLookupNames(name: string): string[] {
  const names = [name];
  const baselineDirPrefix = '__baseline_dir__:';
  if (name.startsWith(baselineDirPrefix)) {
    names.push(name.slice(baselineDirPrefix.length));
  }
  return names;
}

export function isNodeOwnedService(ctx: EmitterContext, ...names: Array<string | undefined>): boolean {
  const configured = nodeOptions(ctx).ownedServices ?? [];
  if (configured.length === 0) return false;

  const owned = new Set(configured.map(normalizeServiceName));
  return names.some((name) =>
    name !== undefined ? ownedLookupNames(name).some((candidate) => owned.has(normalizeServiceName(candidate))) : false,
  );
}

/**
 * True when `name` is a hand-owned type (see {@link NodeEmitterOptions.handOwnedTypes}).
 * Hand-owned types are never generated; the emitter defers to the existing
 * hand-written declaration and routes imports/barrel exports to it.
 */
export function isHandOwnedType(ctx: EmitterContext, name: string | undefined): boolean {
  if (name === undefined) return false;
  const configured = nodeOptions(ctx).handOwnedTypes;
  if (!configured || configured.length === 0) return false;
  return configured.includes(name);
}

/**
 * Resolve the Node operation override for an operation, keyed by "METHOD /path".
 */
export function operationOverrideFor(ctx: EmitterContext, op: Operation): OperationOverride | undefined {
  return nodeOptions(ctx).operationOverrides?.[`${op.httpMethod.toUpperCase()} ${op.path}`];
}

/**
 * `planOperation` plus the Node `responseModel` override. When an operation
 * override supplies `responseModel`, the resolved response model name is
 * replaced so the resource and its generated test reference the desired wire
 * type and deserializer. Use this everywhere the Node emitter would otherwise
 * call `planOperation(op)` directly so resource and test stay in lockstep.
 */
export function planOperationFor(op: Operation, ctx: EmitterContext): OperationPlan {
  const plan = planOperation(op);
  const responseModel = operationOverrideFor(ctx, op)?.responseModel;
  if (responseModel && responseModel !== plan.responseModelName) {
    return { ...plan, responseModelName: responseModel, isModelResponse: true };
  }
  return plan;
}

/**
 * The wire-value → domain-value remap configured for `enumName`, or undefined
 * when the enum is not remapped. See {@link NodeEmitterOptions.enumValueRemaps}.
 */
export function enumValueRemap(ctx: EmitterContext, enumName: string): Record<string, string> | undefined {
  return nodeOptions(ctx).enumValueRemaps?.[enumName];
}

/** True when `enumName` has a configured wire→domain value remap. */
export function isRemappedEnum(ctx: EmitterContext, enumName: string | undefined): boolean {
  return enumName !== undefined && enumValueRemap(ctx, enumName) !== undefined;
}

/** Names of every enum with a configured wire→domain value remap. */
export function remappedEnumNames(ctx: EmitterContext): Set<string> {
  return new Set(Object.keys(nodeOptions(ctx).enumValueRemaps ?? {}));
}

/**
 * Project a raw wire enum value to its SDK-facing domain value via the
 * configured remap (identity when the enum is unmapped or the value has no
 * mapping). Shared by enum/serializer emission and test-assertion generation
 * so they always agree on the domain value.
 */
export function remapWireValueToDomain(ctx: EmitterContext, enumName: string, wireValue: string): string {
  return enumValueRemap(ctx, enumName)?.[wireValue] ?? wireValue;
}

/**
 * The naming convention for the raw-wire companion type of a remapped enum:
 * `DirectoryState` (domain) ↔ `DirectoryStateResponse` (wire).
 */
export function wireEnumName(enumName: string): string {
  return `${enumName}Response`;
}
